### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by vitalyster** [remix-run/react-router#10016]
### What version of React Router are you using?

6.8.0

### Steps to Reproduce

I'm using StaticRouter for SSR. After upgrade to 6.8.0 it started to throw an error.

### Expected Behavior

Version 6.7.0 works as expected

### Actual Behavior

```
TypeError: Cannot read properties of undefined (reading 'pathname')
at Object.createPath (/app/node_modules/@remix-run/router/history.ts:544:3)
at c (/app/node_modules/react-router-dom/index.tsx:422:50)
```

**Comment by draZer0** [comment]
You are probably using a `Link` element without a `to=""` value.

**Comment by vitalyster** [comment]
@draZer0 thanks! I fixed that and now it works. Should the library catch it?
