### ISSUE TITLE
[Bug]: [vite] Internal server error: Failed to resolve entry for package "react-router-dom". The package may have incorrect main/module/exports specified in its package.json.

### ISSUE THREAD

**Issue by highjoon** [remix-run/react-router#10234]
### What version of React Router are you using?

6.9.0

### Steps to Reproduce

```shell
// vite + yarn

yarn add react-router-dom
yarn dev
```

dev scripts : "vite"

### Expected Behavior

application runs correctly

### Actual Behavior

throw an error

```shell
[plugin vite:dep-scan] Failed to resolve entry for package "react-router-dom". The package may have incorrect main/module/exports specified in its package.json.

    node_modules/esbuild/lib/main.js:1365:21:
      1365 │         let result = await callback({
           ╵                      ^

    at packageEntryFailure (file:///D:/Programming/Project/youtube-clone-master/node_modules/vite/dist/node/chunks/dep-ae3fae1b.js:22005:11)
    at resolvePackageEntry (file:///D:/Programming/Project/youtube-clone-master/node_modules/vite/dist/node/chunks/dep-ae3fae1b.js:22002:5)
    at tryNodeResolve (file:///D:/Programming/Project/youtube-clone-master/node_modules/vite/dist/node/chunks/dep-ae3fae1b.js:21737:20)
    at Context.resolveId (file:///D:/Programming/Project/youtube-clone-master/node_modules/vite/dist/node/chunks/dep-ae3fae1b.js:21488:28)
    at Object.resolveId (file:///D:/Programming/Project/youtube-clone-master/node_modules/vite/dist/node/chunks/dep-ae3fae1b.js:41601:46)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async resolve (file:///D:/Programming/Project/youtube-clone-master/node_modules/vite/dist/node/chunks/dep-ae3fae1b.js:41829:26)
    at async file:///D:/Programming/Project/youtube-clone-master/node_modules/vite/dist/node/chunks/dep-ae3fae1b.js:42003:34
    at async requestCallbacks.on-resolve (D:\Programming\Project\youtube-clone-master\node_modules\esbuild\lib\main.js:1365:22)
    at async handleRequest (D:\Programming\Project\youtube-clone-master\node_modules\esbuild\lib\main.js:727:13)

  This error came from the "onResolve" callback registered here:

    node_modules/esbuild/lib/main.js:1287:20:
      1287 │       let promise = setup({
           ╵                     ^

    at setup (file:///D:/Programming/Project/youtube-clone-master/node_modules/vite/dist/node/chunks/dep-ae3fae1b.js:41993:19)
    at handlePlugins (D:\Programming\Project\youtube-clone-master\node_modules\esbuild\lib\main.js:1287:21)
    at buildOrServeImpl (D:\Programming\Project\youtube-clone-master\node_modules\esbuild\lib\main.js:974:5)
    at Object.buildOrServe (D:\Programming\Project\youtube-clone-master\node_modules\esbuild\lib\main.js:780:5)
    at D:\Programming\Project\youtube-clone-master\node_modules\esbuild\lib\main.js:2132:17
    at new Promise (<anonymous>)
    at Object.build (D:\Programming\Project\youtube-clone-master\node_modules\esbuild\lib\main.js:2131:14)
    at build (D:\Programming\Project\youtube-clone-master\node_modules\esbuild\lib\main.js:1978:51)
    at scanImports (file:///D:/Programming/Project/youtube-clone-master/node_modules/vite/dist/node/chunks/dep-ae3fae1b.js:41774:11)

  The plugin "vite:dep-scan" was triggered by this import

    src/main.tsx:4:52:
      4 │ import { createBrowserRouter, RouterProvider } from 'react-router-dom';
        ╵                                                     ~~~~~~~~~~~~~~~~~~

X [ERROR] [plugin vite:dep-scan] Failed to resolve entry for package "react-router-dom". The package may have incorrect main/module/exports specified in its package.json.

    node_modules/esbuild/lib/main.js:1365:21:
      1365 │         let result = await callback({
           ╵                      ^

    at packageEntryFailure (file:///D:/Programming/Project/youtube-clone-master/node_modules/vite/dist/node/chunks/dep-ae3fae1b.js:22005:11)
    at resolvePackageEntry (file:///D:/Programming/Project/youtube-clone-master/node_modules/vite/dist/node/chunks/dep-ae3fae1b.js:22002:5)
    at tryNodeResolve (file:///D:/Programming/Project/youtube-clone-master/node_modules/vite/dist/node/chunks/dep-ae3fae1b.js:21737:20)
    at Context.resolveId (file:///D:/Programming/Project/youtube-clone-master/node_modules/vite/dist/node/chunks/dep-ae3fae1b.js:21488:28)
    at Object.resolveId (file:///D:/Programming/Project/youtube-clone-master/node_modules/vite/dist/node/chunks/dep-ae3fae1b.js:41601:46)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async resolve (file:///D:/Programming/Project/youtube-clone-master/node_modules/vite/dist/node/chunks/dep-ae3fae1b.js:41829:26)
    at async file:///D:/Programming/Project/youtube-clone-master/node_modules/vite/dist/node/chunks/dep-ae3fae1b.js:42003:34
    at async requestCallbacks.on-resolve (D:\Programming\Project\youtube-clone-master\node_modules\esbuild\lib\main.js:1365:22)
    at async handleRequest (D:\Programming\Project\youtube-clone-master\node_modules\esbuild\lib\main.js:727:13)

  This error came from the "onResolve" callback registered here:

    node_modules/esbuild/lib/main.js:1287:20:
      1287 │       let promise = setup({
           ╵                     ^

    at setup (file:///D:/Programming/Project/youtube-clone-master/node_modules/vite/dist/node/chunks/dep-ae3fae1b.js:41993:19)
    at handlePlugins (D:\Programming\Project\youtube-clone-master\node_modules\esbuild\lib\main.js:1287:21)
    at buildOrServeImpl (D:\Programming\Project\youtube-clone-master\node_modules\esbuild\lib\main.js:974:5)
    at Object.buildOrServe (D:\Programming\Project\youtube-clone-master\node_modules\esbuild\lib\main.js:780:5)
    at D:\Programming\Project\youtube-clone-master\node_modules\esbuild\lib\main.js:2132:17
    at new Promise (<anonymous>)
    at Object.build (D:\Programming\Project\youtube-clone-master\node_modules\esbuild\lib\main.js:2131:14)
    at build (D:\Programming\Project\youtube-clone-master\node_modules\esbuild\lib\main.js:1978:51)
    at scanImports (file:///D:/Programming/Project/youtube-clone-master/node_modules/vite/dist/node/chunks/dep-ae3fae1b.js:41774:11)

  The plugin "vite:dep-scan" was triggered by this import

    src/App.tsx:1:23:
      1 │ import { Outlet } from 'react-router-dom';
        ╵                        ~~~~~~~~~~~~~~~~~~

Build failed with 2 errors:
node_modules/esbuild/lib/main.js:1365:21: ERROR: [plugin: vite:dep-scan] Failed to resolve entry for package "react-router-dom". The package may have incorrect main/module/exports specified in its package.json.
node_modules/esbuild/lib/main.js:1365:21: ERROR: [plugin: vite:dep-scan] Failed to resolve entry for package "react-router-dom". The package may have incorrect main/module/exports specified in its package.json.
오후 7:03:10 [vite] Internal server error: Failed to resolve entry for package "react-router-dom". The package may have incorrect main/module/exports specified in its package.json.
  Plugin: vite:import-analysis
  File: D:/Programming/Project/youtube-clone-master/src/main.tsx
      at packageEntryFailure (file:///D:/Programming/Project/youtube-clone-master/node_modules/vite/dist/node/chunks/dep-ae3fae1b.js:22005:11)
      at resolvePackageEntry (file:///D:/Programming/Project/youtube-clone-master/node_modules/vite/dist/node/chunks/dep-ae3fae1b.js:22002:5)
      at tryNodeResolve (file:///D:/Programming/Project/youtube-clone-master/node_modules/vite/dist/node/chunks/dep-ae3fae1b.js:21737:20)
      at Context.resolveId (file:///D:/Programming/Project/youtube-clone-master/node_modules/vite/dist/node/chunks/dep-ae3fae1b.js:21488:28)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async Object.resolveId (file:///D:/Programming/Project/youtube-clone-master/node_modules/vite/dist/node/chunks/dep-ae3fae1b.js:41601:32)
      at async TransformContext.resolve (file:///D:/Programming/Project/youtube-clone-master/node_modules/vite/dist/node/chunks/dep-ae3fae1b.js:41352:23)
      at async normalizeUrl (file:///D:/Programming/Project/youtube-clone-master/node_modules/vite/dist/node/chunks/dep-ae3fae1b.js:39698:34)
      at async TransformContext.transform (file:///D:/Programming/Project/youtube-clone-master/node_modules/vite/dist/node/chunks/dep-ae3fae1b.js:39840:47)
      at async Object.transform (file:///D:/Programming/Project/youtube-clone-master/node_modules/vite/dist/node/chunks/dep-ae3fae1b.js:41674:30)
      at async loadAndTransform (file:///D:/Programming/Project/youtube-clone-master/node_modules/vite/dist/node/chunks/dep-ae3fae1b.js:39479:29)
```

**Comment by highjoon** [comment]
react-router-dom and its deps packages (react-router, @remix/run) are not fully builded.

their package.json's main entry point file (`./dist/index.js` or `./dist/router.cjs.js` etc) are not exist in './dist' directory.

i installed react-router-dom into another project and copied dist folder from react-router-dom, react-router, @remix/run and pasted then into my current project.

and it works

**Comment by timdorr** [comment]
These files definitely exist: https://unpkg.com/browse/react-router-dom@6.9.0/dist/

You have those packages installed incorrectly. That isn't the fault of this library, but something to do with how you installed them. I would delete your `node_modules` folder and reinstall.
