### ISSUE TITLE
[Bug]: url mslformed err 400

### ISSUE THREAD

**Issue by mehdux** [remix-run/react-router#10481]
### What version of React Router are you using?

v6.11.1

### Steps to Reproduce

Enter following url : http://localhost:3001/%

### Expected Behavior

Redirect 404 page

### Actual Behavior

URIError: Failed to decode param '/%'
    at decodeURIComponent (<anonymous>)
    at decode_param (/Users/yassir./workspace/OnboardingFleet/node_modules/express/lib/router/layer.js:172:12)
    at Layer.match (/Users/yassir./workspace/OnboardingFleet/node_modules/express/lib/router/layer.js:123:27)
    at matchLayer (/Users/yassir./workspace/OnboardingFleet/node_modules/express/lib/router/index.js:585:18)
    at next (/Users/yassir./workspace/OnboardingFleet/node_modules/express/lib/router/index.js:226:15)
    at expressInit (/Users/yassir./workspace/OnboardingFleet/node_modules/express/lib/middleware/init.js:40:5)
    at Layer.handle [as handle_request] (/Users/yassir./workspace/OnboardingFleet/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/yassir./workspace/OnboardingFleet/node_modules/express/lib/router/index.js:328:13)
    at /Users/yassir./workspace/OnboardingFleet/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/Users/yassir./workspace/OnboardingFleet/node_modules/express/lib/router/index.js:346:12)

**Comment by mehdux** [comment]
Hi @timdorr ,
the problem comes from the file node_modules/webpack-dev-server/node_modules/express/lib/router/layer.js
Can you change the call to the decodeURIComponent function by the encodeURIComponent function in the decode_param method please because that will solve the problem.
Best regards.

**Comment by timdorr** [comment]
Again, you're talking about the express library. This is React Router. You have the wrong repo.

**Comment by mehdux** [comment]
Hi @timdorr , sorry that's not my intention.
