### ISSUE TITLE
[Bug]: Using `loader` for the `createMemoryRouter` fails a jest test.

### ISSUE THREAD

**Issue by shu512** [remix-run/react-router#11054]
### What version of React Router are you using?

6.20.0

### Steps to Reproduce

[Link to the documentation](https://reactrouter.com/en/main/routers/create-memory-router)

Repo with reproduction:
[Github](https://github.com/shu512/react-router-loader-jest-issue)
[CodeSandbox](https://codesandbox.io/p/github/shu512/react-router-loader-jest-issue/master?layout=%257B%2522sidebarPanel%2522%253A%2522GIT%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clpb4uka300072v6k89fdf11u%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clpb4uka200032v6k390ugpjj%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clpb4uka200052v6kfb33pcke%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clpb4uka200062v6k34p4fvdw%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B100%252C0%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clpb4uka200032v6k390ugpjj%2522%253A%257B%2522id%2522%253A%2522clpb4uka200032v6k390ugpjj%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522clpb4uka200062v6k34p4fvdw%2522%253A%257B%2522id%2522%253A%2522clpb4uka200062v6k34p4fvdw%2522%252C%2522activeTabId%2522%253A%2522clpb55uq800oz2v6ketu5r86p%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%252C%2522id%2522%253A%2522clpb55uq800oz2v6ketu5r86p%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%252C%2522clpb4uka200052v6kfb33pcke%2522%253A%257B%2522id%2522%253A%2522clpb4uka200052v6kfb33pcke%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clpb4uka200042v6khpfooyhm%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clpb4ukds000eefgt6rh59h5q%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522CSB_RUN_OUTSIDE_CONTAINER%253D1%2520devcontainer%2520templates%2520apply%2520--template-id%2520%255C%2522ghcr.io%252Fdevcontainers%252Ftemplates%252Ftypescript-node%255C%2522%2520--template-args%2520%27%257B%257D%27%2520--features%2520%27%255B%255D%27%2522%252C%2522id%2522%253A%2522clpb52t30003q2v6kl8ynb2lm%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522npx%2520jest%2522%252C%2522id%2522%253A%2522clpb52uci00bt2v6kow9vz9cv%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clpb52uci00bt2v6kow9vz9cv%2522%257D%257D%252C%2522showDevtools%2522%253Afalse%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)
[StackBlitz](https://stackblitz.com/~/github.com/shu512/react-router-loader-jest-issue)

Example:

```
import {
    RouterProvider,
    createMemoryRouter,
} from "react-router-dom";
import { render } from "@testing-library/react";
import "@testing-library/jest-dom";
  
test('failed', async () => {
    const routes = [
      {
        path: '/',
        element: <div />,
        loader: () => ({ name: 'test event' }), // if comment this line the test is passed
      },
    ];
  
    const router = createMemoryRouter(routes, {
      initialEntries: ['/'],
    });
  
    render(<RouterProvider router={router} />);
  
    expect(1).toBe(1);
});
```

### Expected Behavior

The test is passed

### Actual Behavior

Test failed with error: `TypeError: Request is not a constructor`

<details> 
  <summary>StackTrace</summary>

   TypeError: Request is not a constructor

    at createClientSideRequest (/home/shu512/react-router-loader-jest-issue/node_modules/@remix-run/router/dist/router.cjs.js:4223:10)

    at startNavigation (/home/shu512/react-router-loader-jest-issue/node_modules/@remix-run/router/dist/router.cjs.js:2252:19)

    at Object.initialize (/home/shu512/react-router-loader-jest-issue/node_modules/@remix-run/router/dist/router.cjs.js:1898:7)

    at createMemoryRouter (/home/shu512/react-router-loader-jest-issue/node_modules/react-router/dist/umd/react-router.development.js:1368:8)

    at Object.eval (/home/shu512/react-router-loader-jest-issue/src/failed.test.tsx:15:62)

    at Promise.then.completed (/home/shu512/react-router-loader-jest-issue/node_modules/jest-circus/build/utils.js:298:28)

    at callAsyncCircusFn (/home/shu512/react-router-loader-jest-issue/node_modules/jest-circus/build/utils.js:231:10)

    at _callCircusTest (/home/shu512/react-router-loader-jest-issue/node_modules/jest-circus/build/run.js:316:40)

    at async _runTest (/home/shu512/react-router-loader-jest-issue/node_modules/jest-circus/build/run.js:252:3)

    at async _runTestsForDescribeBlock (/home/shu512/react-router-loader-jest-issue/node_modules/jest-circus/build/run.js:126:9)

    at async run (/home/shu512/react-router-loader-jest-issue/node_modules/jest-circus/build/run.js:71:3)

    at async runAndTransformResultsToJestFormat (/home/shu512/react-router-loader-jest-issue/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterInit.js:122:21)

    at async jestAdapter (/home/shu512/react-router-loader-jest-issue/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:79:19)

    at async runTestInternal (/home/shu512/react-router-loader-jest-issue/node_modules/jest-runner/build/runTest.js:367:16)

    at async runTest (/home/shu512/react-router-loader-jest-issue/node_modules/jest-runner/build/runTest.js:444:34)
</details>

Initially I had propblems in my project with different error:

<details> 
  <summary>StackTrace</summary>

TypeError: Cannot read properties of undefined (reading 'addEventListener')

    at callLoaderOrAction (/home/shu512/react-router-loader-jest-issue/node_modules/.pnpm/@remix-run+router@1.3.3/node_modules/@remix-run/router/router.ts:3116:18)
    
    at map (/home/shu512/react-router-loader-jest-issue/node_modules/.pnpm/@remix-run+router@1.3.3/node_modules/@remix-run/router/router.ts:2024:9)
    
    at Array.map (<anonymous>)
    
    at callLoadersAndMaybeResolveData (/home/shu512/react-router-loader-jest-issue/node_modules/.pnpm/@remix-run+router@1.3.3/node_modules/@remix-run/router/router.ts:2023:24)
    
    at handleLoaders (/home/shu512/react-router-loader-jest-issue/node_modules/.pnpm/@remix-run+router@1.3.3/node_modules/@remix-run/router/router.ts:1448:13)
    
    at startNavigation (/home/shu512/react-router-loader-jest-issue/node_modules/.pnpm/@remix-run+router@1.3.3/node_modules/@remix-run/router/router.ts:1211:56)
    
    at Object.initialize (/home/shu512/react-router-loader-jest-issue/node_modules/.pnpm/@remix-run+router@1.3.3/node_modules/@remix-run/router/router.ts:842:7)
    
    at createMemoryRouter (/home/shu512/react-router-loader-jest-issue/node_modules/.pnpm/react-router@6.8.2_react@18.2.0/node_modules/react-router/index.ts:224:6)
    
    at Object.<anonymous> (/home/shu512/react-router-loader-jest-issue/src/pages/edit-shipment-page/documents/document-edit/lib/DocumentIsNotGeneratedGuard.test.tsx:51:62)
    
    at Promise.then.completed (/home/shu512/react-router-loader-jest-issue/node_modules/.pnpm/jest-circus@29.5.0/node_modules/jest-circus/build/utils.js:293:28)
    
    at new Promise (<anonymous>)
    
    at callAsyncCircusFn (/home/shu512/react-router-loader-jest-issue/node_modules/.pnpm/jest-circus@29.5.0/node_modules/jest-circus/build/utils.js:226:10)
    
    at _callCircusTest (/home/shu512/react-router-loader-jest-issue/node_modules/.pnpm/jest-circus@29.5.0/node_modules/jest-circus/build/run.js:297:40)
    
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    
    at async _runTest (/home/shu512/react-router-loader-jest-issue/node_modules/.pnpm/jest-circus@29.5.0/node_modules/jest-circus/build/run.js:233:3)
    
    at async _runTestsForDescribeBlock (/home/shu512/react-router-loader-jest-issue/node_modules/.pnpm/jest-circus@29.5.0/node_modules/jest-circus/build/run.js:135:9)
    
    at async run (/home/shu512/react-router-loader-jest-issue/node_modules/.pnpm/jest-circus@29.5.0/node_modules/jest-circus/build/run.js:68:3)
    
    at async runAndTransformResultsToJestFormat (/home/shu512/react-router-loader-jest-issue/node_modules/.pnpm/jest-circus@29.5.0/node_modules/jest-circus/build/legacy-code-todo-rewrite/
    jestAdapterInit.js:122:21)
    at async jestAdapter (/home/shu512/react-router-loader-jest-issue/node_modules/.pnpm/jest-circus@29.5.0/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:79:19)
    
    at async runTestInternal (/home/shu512/react-router-loader-jest-issue/node_modules/.pnpm/jest-runner@29.5.0/node_modules/jest-runner/build/runTest.js:367:16)
    
    at async runTest (/home/shu512/react-router-loader-jest-issue/node_modules/.pnpm/jest-runner@29.5.0/node_modules/jest-runner/build/runTest.js:444:34)
    
</details> 

That's my first bug report, so I hope I did it in a good way.

Give me a sign, if I can improve it.

Thanks!

**Comment by timdorr** [comment]
Because you're emulating a browser environment with jsdom, you need to mock Request. You can use our approach here: https://github.com/remix-run/react-router/blob/main/packages/router/__tests__/setup.ts
