### ISSUE TITLE
[Bug]: v7pre - Cursor: Couldn't find @react-router/dev

### ISSUE THREAD

**Issue by shmuli9** [remix-run/react-router#12081]
### What version of React Router are you using?

7.0.0-pre.0

### Steps to Reproduce

Use Cursor to setup a project (using `npx degit remix-run/react-router/templates/basic#dev my-app`)

Create route file at `app/routes/page.tsx`
Add a route for that file in `app/routes.ts`

```typescript
export const routes: RouteConfig = [
    route("page/:slug", "routes/page.tsx"),
];
```

Back in `page.tsx`, unable to import route type `import type * as Route from "./+types.page";` as the `.react-router` dir is not created/types have not been generated

Open TS Server Logs, and see the line: 
`Info 27   [13:03:20.939] Couldn't find @react-router/dev`

This seems to be due to being unable to find the correct binaries:
```
Info 26   [13:03:20.939] Failed to load module '@react-router/dev' from /home/user/.cursor-server/bin/51c8aff7cb5a89f4a0e462fbacab938bdbfaf140/extensions/node_modules/node_modules: Error: Could not resolve JS module '@react-router/dev' starting at '/home/user/.cursor-server/bin/51c8aff7cb5a89f4a0e462fbacab938bdbfaf140/extensions/node_modules/node_modules'. Looked in: /home/user/.cursor-server/bin/51c8aff7cb5a89f4a0e462fbacab938bdbfaf140/extensions/node_modules/@react-router/dev/package.json, /home/user/.cursor-server/bin/51c8aff7cb5a89f4a0e462fbacab938bdbfaf140/extensions/node_modules/@react-router/dev.js, /home/user/.cursor-server/bin/51c8aff7cb5a89f4a0e462fbacab938bdbfaf140/extensions/node_modules/@react-router/dev.jsx, /home/user/.cursor-server/bin/51c8aff7cb5a89f4a0e462fbacab938bdbfaf140/extensions/node_modules/@react-router/dev/index.js, /home/user/.cursor-server/bin/51c8aff7cb5a89f4a0e462fbacab938bdbfaf140/extensions/node_modules/@react-router/dev/index.jsx, /home/user/.cursor-server/bin/51c8aff7cb5a89f4a0e462fbacab938bdbfaf140/node_modules/@react-router/dev/package.json, /home/user/.cursor-server/bin/51c8aff7cb5a89f4a0e462fbacab938bdbfaf140/node_modules/@react-router/dev.js, /home/user/.cursor-server/bin/51c8aff7cb5a89f4a0e462fbacab938bdbfaf140/node_modules/@react-router/dev.jsx, /home/user/.cursor-server/bin/51c8aff7cb5a89f4a0e462fbacab938bdbfaf140/node_modules/@react-router/dev/index.js, /home/user/.cursor-server/bin/51c8aff7cb5a89f4a0e462fbacab938bdbfaf140/node_modules/@react-router/dev/index.jsx, /home/user/.cursor-server/bin/node_modules/@react-router/dev/package.json, /home/user/.cursor-server/bin/node_modules/@react-router/dev.js, /home/user/.cursor-server/bin/node_modules/@react-router/dev.jsx, /home/user/.cursor-server/bin/node_modules/@react-router/dev/index.js, /home/user/.cursor-server/bin/node_modules/@react-router/dev/index.jsx, /home/user/.cursor-server/node_modules/@react-router/dev/package.json, /home/user/.cursor-server/node_modules/@react-router/dev.js, /home/user/.cursor-server/node_modules/@react-router/dev.jsx, /home/user/.cursor-server/node_modules/@react-router/dev/index.js, /home/user/.cursor-server/node_modules/@react-router/dev/index.jsx, /home/user/node_modules/@react-router/dev/package.json, /home/user/node_modules/@react-router/dev.js, /home/user/node_modules/@react-router/dev.jsx, /home/user/node_modules/@react-router/dev/index.js, /home/user/node_modules/@react-router/dev/index.jsx, /home/node_modules/@react-router/dev/package.json, /home/node_modules/@react-router/dev.js, /home/node_modules/@react-router/dev.jsx, /home/node_modules/@react-router/dev/index.js, /home/node_modules/@react-router/dev/index.jsx, /node_modules/@react-router/dev/package.json, /node_modules/@react-router/dev.js, /node_modules/@react-router/dev.jsx, /node_modules/@react-router/dev/index.js, /node_modules/@react-router/dev/index.jsx
    at resolveJSModule (/home/user/.cursor-server/bin/51c8aff7cb5a89f4a0e462fbacab938bdbfaf140/extensions/node_modules/typescript/lib/typescript.js:44094:11)
    at Object.require (/home/user/.cursor-server/bin/51c8aff7cb5a89f4a0e462fbacab938bdbfaf140/extensions/node_modules/typescript/lib/typescript.js:8542:30)
    at _Project.importServicePluginSync (/home/user/.cursor-server/bin/51c8aff7cb5a89f4a0e462fbacab938bdbfaf140/extensions/node_modules/typescript/lib/typescript.js:182283:27)
    at _ProjectService.requestEnablePlugin (/home/user/.cursor-server/bin/51c8aff7cb5a89f4a0e462fbacab938bdbfaf140/extensions/node_modules/typescript/lib/typescript.js:187834:16)
    at ConfiguredProject2.enablePlugin (/home/user/.cursor-server/bin/51c8aff7cb5a89f4a0e462fbacab938bdbfaf140/extensions/node_modules/typescript/lib/typescript.js:183593:25)
    at ConfiguredProject2.enablePluginsWithOptions (/home/user/.cursor-server/bin/51c8aff7cb5a89f4a0e462fbacab938bdbfaf140/extensions/node_modules/typescript/lib/typescript.js:184354:14)
    at _ProjectService.loadConfiguredProject (/home/user/.cursor-server/bin/51c8aff7cb5a89f4a0e462fbacab938bdbfaf140/extensions/node_modules/typescript/lib/typescript.js:186133:13)
    at _ProjectService.reloadConfiguredProject (/home/user/.cursor-server/bin/51c8aff7cb5a89f4a0e462fbacab938bdbfaf140/extensions/node_modules/typescript/lib/typescript.js:186385:10)
    at ConfiguredProject2.updateGraph (/home/user/.cursor-server/bin/51c8aff7cb5a89f4a0e462fbacab938bdbfaf140/extensions/node_modules/typescript/lib/typescript.js:184283:29)
    at updateWithTriggerFile (/home/user/.cursor-server/bin/51c8aff7cb5a89f4a0e462fbacab938bdbfaf140/extensions/node_modules/typescript/lib/typescript.js:184770:11)
    at updateConfiguredProject (/home/user/.cursor-server/bin/51c8aff7cb5a89f4a0e462fbacab938bdbfaf140/extensions/node_modules/typescript/lib/typescript.js:184778:9)
    at _ProjectService.findCreateOrReloadConfiguredProject (/home/user/.cursor-server/bin/51c8aff7cb5a89f4a0e462fbacab938bdbfaf140/extensions/node_modules/typescript/lib/typescript.js:187247:44)
    at _ProjectService.tryFindDefaultConfiguredProjectForOpenScriptInfo (/home/user/.cursor-server/bin/51c8aff7cb5a89f4a0e462fbacab938bdbfaf140/extensions/node_modules/typescript/lib/typescript.js:187271:25)
    at _ProjectService.tryFindDefaultConfiguredProjectAndLoadAncestorsForOpenScriptInfo (/home/user/.cursor-server/bin/51c8aff7cb5a89f4a0e462fbacab938bdbfaf140/extensions/node_modules/typescript/lib/typescript.js:187317:25)
    at _ProjectService.assignProjectToOpenedScriptInfo (/home/user/.cursor-server/bin/51c8aff7cb5a89f4a0e462fbacab938bdbfaf140/extensions/node_modules/typescript/lib/typescript.js:187202:27)
    at /home/user/.cursor-server/bin/51c8aff7cb5a89f4a0e462fbacab938bdbfaf140/extensions/node_modules/typescript/lib/typescript.js:187575:25
    at Array.forEach (<anonymous>)
    at _ProjectService.applyChangesInOpenFiles (/home/user/.cursor-server/bin/51c8aff7cb5a89f4a0e462fbacab938bdbfaf140/extensions/node_modules/typescript/lib/typescript.js:187573:56)
    at updateOpen (/home/user/.cursor-server/bin/51c8aff7cb5a89f4a0e462fbacab938bdbfaf140/extensions/node_modules/typescript/lib/typescript.js:188764:29)
    at /home/user/.cursor-server/bin/51c8aff7cb5a89f4a0e462fbacab938bdbfaf140/extensions/node_modules/typescript/lib/typescript.js:191397:69
    at IpcIOSession.executeWithRequestId (/home/user/.cursor-server/bin/51c8aff7cb5a89f4a0e462fbacab938bdbfaf140/extensions/node_modules/typescript/lib/typescript.js:191389:14)
    at IpcIOSession.executeCommand (/home/user/.cursor-server/bin/51c8aff7cb5a89f4a0e462fbacab938bdbfaf140/extensions/node_modules/typescript/lib/typescript.js:191397:29)
    at IpcIOSession.onMessage (/home/user/.cursor-server/bin/51c8aff7cb5a89f4a0e462fbacab938bdbfaf140/extensions/node_modules/typescript/lib/typescript.js:191439:51)
    at process.<anonymous> (/home/user/.cursor-server/bin/51c8aff7cb5a89f4a0e462fbacab938bdbfaf140/extensions/node_modules/typescript/lib/tsserver.js:523:14)
    at process.emit (node:events:518:28)
    at emit (node:internal/child_process:951:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
```

### Expected Behavior

Types should be generated automatically via the TS plugin as you type/save, no manual commands necessary when using Cursor IDE

### Actual Behavior

You need to run `react-router typegen` manually, to create the types directory, and then again to keep them up to date with changes when using Cursor
VSC seems to work fine

**Comment by shmuli9** [comment]
This was due to the fact that Cursor wasn't using the workspace version of typescript for some reason

Fix is: Ctrl/Cmd-Shift-P, `Select Typescript Version` and selecting the workspace version
