### ISSUE TITLE
[Bug]: When I use useNavigate hook in my project, it got error for not good use of hook ,But I use hook as tutorial

### ISSUE THREAD

**Issue by wangyang875** [remix-run/react-router#12107]
### What version of React Router are you using?

 "react-router-dom": "6.26.2",

### Steps to Reproduce

```
const router = createBrowserRouter([{
  path: '/', element: LogIn()
}, { path: 'hall', element: Hall() }])

const root = ReactDOM.createRoot(
  document.getElementById('root') as HTMLElement
);
root.render(
  <React.StrictMode>
    <Provider store={store}>
      <RouterProvider router={router}></RouterProvider>
    </Provider>
  </React.StrictMode>
);
```

```
import React from "react";
import { useNavigate } from "react-router-dom";
function Hall() {
    const navi = useNavigate()
    function handle() {
        navi('/hall')
    }
    return(
         <div>  
            <Button>
            OK
        </Button></div>
    )
}
export default Hall;

```

### Expected Behavior

no error 

### Actual Behavior

window is blank , and got error on colsole;
```
index.tsx:9 Warning: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
printWarning @ react.development.js:209
error @ react.development.js:183
resolveDispatcher @ react.development.js:1592
useContext @ react.development.js:1602
useNavigate @ index.js:195
Hall @ index.tsx:9
./src/index.tsx @ index.tsx:15
__webpack_require__ @ bootstrap:22
(anonymous) @ startup:6
(anonymous) @ startup:6
Show 5 more frames
Show less
react.development.js:1618 Uncaught TypeError: Cannot read properties of null (reading 'useContext')
    at Object.useContext (react.development.js:1618:1)
    at useNavigate (index.js:195:7)
    at Hall (index.tsx:9:1)
    at ./src/index.tsx (index.tsx:15:10)
    at __webpack_require__ (bootstrap:22:1)
    at startup:6:1
    at startup:6:1

```

![image](https://github.com/user-attachments/assets/3197b8ca-53f5-4f5c-b8bb-df7014feafd1)

**Comment by wangyang875** [comment]
there is only one react version that is 18.3.1

**Comment by timdorr** [comment]
This isn't a React Router error. This doesn't have to do with the library.
