### ISSUE TITLE
[Bug]: (v7) Layout routes params are generated as an empty object missing actual params

### ISSUE THREAD

**Issue by DovydasNavickas** [remix-run/react-router#12178]
### What version of React Router are you using?

7.0.0-pre.1

### Steps to Reproduce

1. Clone repo: https://github.com/DovydasNavickas/react-router-layout-bug
2. Run the project with local typescript version enabled in VS Code for typescript plugin to work.
3. An error is in file `/app/routes/layouts/main.tsx`

### Expected Behavior

Layout params have route params just as any other route.

### Actual Behavior

The layout effectively gets the route params and route params type is generated, but it is empty.

**Comment by jam-fran** [comment]
Also running into this issue. I have a layout route that 1) has dynamic route segment and 2) loads some data. The types for the route's `ComponentProps` are generated correctly, but the types for the dynamic route segment in the params prop are not.

**Comment by blry** [comment]
Check https://api.reactrouter.com/v7/functions/react_router.useParams.html

**Comment by pcattori** [comment]
Fixed by https://github.com/remix-run/react-router/pull/13543 . The release process for v7.6.0 started before that PR was merged, so this will make it into the next release after v7.6.0

**Comment by asieraduriz** [comment]
I can reproduce the same issue.
Now, `npx create-react-router@latest` outputs these dependencies
```
  "dependencies": {
    "@react-router/node": "^7.6.3",
    "@react-router/serve": "^7.6.3",
    "isbot": "^5.1.27",
    "react": "^19.1.0",
    "react-dom": "^19.1.0",
    "react-router": "^7.6.3"
  },
  "devDependencies": {
    "@react-router/dev": "^7.6.3",
    "@tailwindcss/vite": "^4.1.4",
    "@types/node": "^20",
    "@types/react": "^19.1.2",
    "@types/react-dom": "^19.1.2",
    "tailwindcss": "^4.1.4",
    "typescript": "^5.8.3",
    "vite": "^6.3.3",
    "vite-tsconfig-paths": "^5.1.4"
  }
```

Extend `routes.tsx` with this
```tsx
import { type RouteConfig, index, route } from '@react-router/dev/routes'

export default [
  index('routes/home.tsx'),
  route(':lang?/about-us/:pageName?', 'routes/about-us.tsx'),
] satisfies RouteConfig
```

and in `routes/about-us.tsx` have
```
import type { Route } from './+types/home'

export async function loader({ params }: Route.LoaderArgs) {
  return {
    title: 'About us',
  }
}

export default function RouteComponent({}: Route.ComponentProps) {
  return <div>Route component</div>
}
```

Params is still an empty object `{ }`

<img width="1709" height="399" alt="Image" src="https://github.com/user-attachments/assets/96e896b2-3c72-4e36-8b99-e7896af13b26" />

<img width="1678" height="394" alt="Image" src="https://github.com/user-attachments/assets/ed39ab79-47b4-49d5-b030-86dc68a5cfe9" />

**Comment by justinbarrett-loa** [comment]
I'm seeing the same thing as @asieraduriz after updating to 7.6.3. Please reopen this issue.

**Comment by pcattori** [comment]
@asieraduriz , I tried to reproduce this locally when I noticed that you have the wrong import in `routes/about-us.tsx`:

```ts
import type { Route } from './+types/home'
// should be './+types/about-us' 👆
```

Once I fixed that import, then types for `param` were correct:

<img width="1051" height="474" alt="Image" src="https://github.com/user-attachments/assets/34bae334-2c08-4c99-8096-b7c4e58df193" />

---

@justinbarrett-loa did you also have a mismatched types import? If not, could you share a reproduction?

**Comment by justinbarrett-loa** [comment]
@pcattori Here's my `routes.ts` file:

```ts
import {
  type RouteConfig,
  index,
  prefix,
  route
} from "@react-router/dev/routes";

export default [
  index("./routes/index.tsx"),
  route("directory", "./routes/directory.tsx"),

  ...prefix("admin", [
    route("roles", "./routes/admin/roles.tsx"),
    route("users", "./routes/admin/users.tsx"),
    route("users/:userId", "./routes/admin/user.tsx"),
  ]),

  ...prefix("install", [
    route("visits", "./routes/install/visits.tsx"),
  ]),

  ...prefix("it", [
    route("logs", "./routes/it/logs.tsx"),
    route("resources", "./routes/it/resources.tsx"),
    route("settings", "./routes/it/settings.tsx"),
  ]),

  ...prefix("sales", [
    route("contacts", "./routes/sales/contacts/contacts.tsx"),
    route("contacts/:contactId", "./routes/sales/contacts/contact.tsx"),
    route("deals", "./routes/sales/deals.tsx"),
    route("locations", "./routes/sales/locations.tsx"),
    route("settings", "./routes/sales/settings/settings.tsx")
  ])
] satisfies RouteConfig;
```

I updated to 7.6.3 from 7.2.?, and all of the component files use the format `import { Route } from "../../+types"`. With my `routes.ts` file as above, the only autocomplete options that I get to put another path after `+types` are "index" and "directory". Is this because all of my other routes are in `prefix` groups?

**Comment by pcattori** [comment]
@justinbarrett-loa could you share a StackBlitz or GitHub link for your reproduction? That way I can prioritize this in our backlog

**Comment by justinbarrett-loa** [comment]
@pcattori Here's my reproduction repo:

https://github.com/justinbarrett-loa/rrParamsProblem

FWIW I ran into even more problems just getting that put together. I started with:

```sh
npx create-react-router@latest rrParamsProblem
```

After everything was installed I did `npm i` (which didn't install anything new), then tried to run `npm run dev`, but got the following errors:

```
✘ [ERROR] No matching export in "node_modules/react-router/dist/development/index.mjs" for import "UNSAFE_useRoutesImpl"

    ../../../../node_modules/react-router-dom/dist/index.js:13:101:
      13 │ ...erties, UNSAFE_DataRouterContext, UNSAFE_DataRouterStateContext, Router, UNSAFE_useRoutesImpl, UNSAFE_NavigationContext, useHref, useResolvedPath, useLocation, useNav...
         ╵                                                                             ~~~~~~~~~~~~~~~~~~~~

✘ [ERROR] No matching export in "node_modules/react-router/dist/development/index.mjs" for import "UNSAFE_useRouteId"

    ../../../../node_modules/react-router-dom/dist/index.js:13:213:
      13 │ ...onContext, useHref, useResolvedPath, useLocation, useNavigate, createPath, UNSAFE_useRouteId, UNSAFE_RouteContext, useMatches, useNavigation, useBlocker } from 'react...
         ╵                                                                               ~~~~~~~~~~~~~~~~~

✘ [ERROR] No matching export in "node_modules/react-router/dist/development/index.mjs" for import "AbortedDeferredError"

    ../../../../node_modules/react-router-dom/dist/index.js:14:9:
      14 │ export { AbortedDeferredError, Await, MemoryRouter, Navigate, NavigationType, Outlet, Route, Router, Routes, UNSAFE_DataRouterContext, UNSAFE_DataRouterStateContext, UNS...
         ╵          ~~~~~~~~~~~~~~~~~~~~

✘ [ERROR] No matching export in "node_modules/react-router/dist/development/index.mjs" for import "UNSAFE_useRouteId"

    ../../../../node_modules/react-router-dom/dist/index.js:14:237:
      14 │ ...xt, UNSAFE_LocationContext, UNSAFE_NavigationContext, UNSAFE_RouteContext, UNSAFE_useRouteId, createMemoryRouter, createPath, createRoutesFromChildren, createRoutesFr...
         ╵                                                                               ~~~~~~~~~~~~~~~~~

✘ [ERROR] No matching export in "node_modules/react-router/dist/development/index.mjs" for import "defer"

    ../../../../node_modules/react-router-dom/dist/index.js:14:340:
      14 │ ...ateMemoryRouter, createPath, createRoutesFromChildren, createRoutesFromElements, defer, generatePath, isRouteErrorResponse, json, matchPath, matchRoutes, parsePath, r...
         ╵                                                                                     ~~~~~

✘ [ERROR] No matching export in "node_modules/react-router/dist/development/index.mjs" for import "json"

    ../../../../node_modules/react-router-dom/dist/index.js:14:383:
      14 │ ...omChildren, createRoutesFromElements, defer, generatePath, isRouteErrorResponse, json, matchPath, matchRoutes, parsePath, redirect, redirectDocument, renderMatches, r...
         ╵                                                                                     ~~~~

/Users/justinbarrett/Documents/dev/personal/rrParamsProblem/node_modules/esbuild/lib/main.js:1465
  let error = new Error(text);
              ^

Error: Build failed with 6 errors:
../../../../node_modules/react-router-dom/dist/index.js:13:101: ERROR: No matching export in "node_modules/react-router/dist/development/index.mjs" for import "UNSAFE_useRoutesImpl"
../../../../node_modules/react-router-dom/dist/index.js:13:213: ERROR: No matching export in "node_modules/react-router/dist/development/index.mjs" for import "UNSAFE_useRouteId"
../../../../node_modules/react-router-dom/dist/index.js:14:9: ERROR: No matching export in "node_modules/react-router/dist/development/index.mjs" for import "AbortedDeferredError"
../../../../node_modules/react-router-dom/dist/index.js:14:237: ERROR: No matching export in "node_modules/react-router/dist/development/index.mjs" for import "UNSAFE_useRouteId"
../../../../node_modules/react-router-dom/dist/index.js:14:340: ERROR: No matching export in "node_modules/react-router/dist/development/index.mjs" for import "defer"
...
    at failureErrorWithLog (/Users/justinbarrett/Documents/dev/personal/rrParamsProblem/node_modules/esbuild/lib/main.js:1465:15)
    at /Users/justinbarrett/Documents/dev/personal/rrParamsProblem/node_modules/esbuild/lib/main.js:924:25
    at /Users/justinbarrett/Documents/dev/personal/rrParamsProblem/node_modules/esbuild/lib/main.js:1343:9
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  errors: [Getter/Setter],
  warnings: [Getter/Setter]
}

Node.js v21.7.3
```

I went ahead and added my test with the `prefix` setup like I mentioned above. Not only do I not get autocomplete after `+types` in the `test.tsx` file, but that import already indicates an error:

<img width="907" height="268" alt="Image" src="https://github.com/user-attachments/assets/007f786d-c241-4548-98cf-05107da3855d" />

I tried multiple subpaths, and even though `+types` comes up in a few of them, they still indicate a similar error.

**Comment by pcattori** [comment]
@justinbarrett-loa you should be using `"./+types/testing"` as the import source for `Route`, not `"../+types"` (see https://reactrouter.com/explanation/type-safety):

<img width="953" height="338" alt="Image" src="https://github.com/user-attachments/assets/263ba561-d16b-4385-b763-60dee39b3a8b" />

I can also confirm that autocomplete for the types import source works as expected as long as you start with the correct relative path (`./`, not `../`):

<img width="578" height="116" alt="Image" src="https://github.com/user-attachments/assets/a3e20262-8928-4178-bc7d-ca1f3ee25fd1" />

**Comment by justinbarrett-loa** [comment]
@pcattori Thanks for the correction. I only left `../+types` in there because I couldn't figure out the correct path. I hadn't seen that page on type safety yet. I feel that it might help to surface that info earlier in the docs, though off the top of my head I'm not sure where.

**Comment by asieraduriz** [comment]
> [@asieraduriz](https://github.com/asieraduriz) , I tried to reproduce this locally when I noticed that you have the wrong import in `routes/about-us.tsx`:
> 
> import type { Route } from './+types/home'
> // should be './+types/about-us' 👆
> Once I fixed that import, then types for `param` were correct:
> 
> <img alt="Image" width="1051" height="474" src="https://private-user-images.githubusercontent.com/1477317/463745850-34bae334-2c08-4c99-8096-b7c4e58df193.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTM3MDYwNjUsIm5iZiI6MTc1MzcwNTc2NSwicGF0aCI6Ii8xNDc3MzE3LzQ2Mzc0NTg1MC0zNGJhZTMzNC0yYzA4LTRjOTktODA5Ni1iN2M0ZTU4ZGYxOTMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDcyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTA3MjhUMTIyOTI1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjZjZDU0ZmVhZWRlNWM4NDdkZWRjZWVkOGMzYTBkNTYyODljNDUyZWIxYzRmOTNmZjgyMTc5YTlmZGQwYzRkNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.w6AbgNAUEuLI7xkYaNtnw87aIbVXP1HhzLc8wrunRlY">
> [@justinbarrett-loa](https://github.com/justinbarrett-loa) did you also have a mismatched types import? If not, could you share a reproduction?

OMG! Such a rookie mistake, so sorry! After the fix, I can see it working properly, thank you and apologies again.

Without intending to change the issue into another question. Is there a way to have multiple routes pointing to the same module?
Example:
- `/landing-pages/:slug?`
- `/template-landing-pages/:slug?`
These two routes point to the same `LandingPage.tsx`? Is it possible?

**Comment by pcattori** [comment]
> Without intending to change the issue into another question. Is there a way to have multiple routes pointing to the same module? Example:
> 
> * `/landing-pages/:slug?`
> * `/template-landing-pages/:slug?`
>   These two routes point to the same `LandingPage.tsx`? Is it possible?

Yes, you'll need to manually set route IDs like so:

```ts
// app/routes.ts

import { type RouteConfig, index, route } from "@react-router/dev/routes";

export default [
  route("/landing-pages/:slug?", "routes/LandingPage.tsx", { id: "landing-page" }),
  route("/template-landing-pages/:slug?", "routes/LandingPage.tsx", { id: "template-landing-page" }),
] satisfies RouteConfig;
```
