### ISSUE TITLE
[Bug]: (v7) Error: Expected a Response to be returned from resource route handler

### ISSUE THREAD

**Issue by bryanjtc** [remix-run/react-router#12181]
### What version of React Router are you using?

7.0.0-pre.1

### Steps to Reproduce

Clone this repo: https://github.com/bryanjtc/openapi-react-query-codegen/tree/react-router-examples
Run pnpm install
Run pnpm -F=@7nohe/react-router-7-app dev

### Expected Behavior

No error

### Actual Behavior

I have this error
```shell
Error: Expected a Response to be returned from resource route handler
    at invariant (G:\repo\openapi-react-query-codegen\node_modules\.pnpm\react-router@7.0.0-pre.1_react-dom@18.3.1_react@18.3.1__react@18.3.1\node_modules\react-router\lib\server-runtime\invariant.ts:14:11)
    at handleResourceRequest (G:\repo\openapi-react-query-codegen\node_modules\.pnpm\react-router@7.0.0-pre.1_react-dom@18.3.1_react@18.3.1__react@18.3.1\node_modules\react-router\lib\server-runtime\server.ts:497:5)
    at requestHandler (G:\repo\openapi-react-query-codegen\node_modules\.pnpm\react-router@7.0.0-pre.1_react-dom@18.3.1_react@18.3.1__react@18.3.1\node_modules\react-router\lib\server-runtime\server.ts:199:18)
    at nodeHandler (G:\repo\openapi-react-query-codegen\node_modules\.pnpm\@react-router+dev@7.0.0-pre.1_@react-router+serve@7.0.0-pre.1_react-router@7.0.0-pre.1_react-_dq2yadundj6pg3jjpzr7cixyk4\node_modules\@react-router\dev\dist\vite\plugin.js:733:27)
    at G:\repo\openapi-react-query-codegen\node_modules\.pnpm\@react-router+dev@7.0.0-pre.1_@react-router+serve@7.0.0-pre.1_react-router@7.0.0-pre.1_react-_dq2yadundj6pg3jjpzr7cixyk4\node_modules\@react-router\dev\dist\vite\plugin.js:736:15
```

**Comment by bryanjtc** [comment]
I may be getting ahead of myself considering v7 is still in alpha. I wanted to try @tanstack/react-query with my favorite open-api codegen. I use a combination of the @tanstack/react-query [remix guide](https://tanstack.com/query/latest/docs/framework/react/guides/ssr) with the new rr7 vite provider [docs](https://reactrouter.com/dev/guides/upgrading/vite-router-provider)

**Comment by bryanjtc** [comment]
I found an example on the dev branch. They changed export function Component with export default. That fixes it
