### ISSUE TITLE
API Routes not working

### ISSUE THREAD

**Issue by KwaminaWhyte** [remix-run/react-router#12411]
### I'm using React Router as a...

framework

### Reproduction

I did this in routes.ts

```
...prefix('api/v1', [
    route('register', './routes/apis/v1/register.ts'),
    route('login', './routes/apis/v1/login.ts'),
  ]),
```

### System Info

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (4) x64 Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz
    Memory: 3.51 GB / 15.92 GB
  Binaries:
    Node: 20.18.1 - C:\Program Files\nodejs\node.EXE     
    npm: 10.8.2 - C:\Program Files\nodejs\npm.CMD        
    bun: 1.1.36 - ~\.bun\bin\bun.EXE
  Browsers:
    Edge: Chromium (131.0.2903.63)
    Internet Explorer: 11.0.19041.4355
  npmPackages:
    @react-router/dev: ^7.0.1 => 7.0.1 
    @react-router/node: ^7.0.1 => 7.0.1 
    @react-router/serve: ^7.0.1 => 7.0.1 
    react-router: ^7.0.1 => 7.0.1 
    vite: ^5.4.11 => 5.4.11
```

### Used Package Manager

npm

### Expected Behavior

To return json response

### Actual Behavior

```
The following error is a bug in React Router; please open an issue! https://github.com/remix-run/react-router/issues/new/choose
Error: Expected a Response to be returned from resource route handler
    at invariant3 (C:\projects\_pewvegas\pm-travels-and-tours-website\node_modules\react-router\dist\production\index.js:8684:11)   
    at handleResourceRequest (C:\projects\_pewvegas\pm-travels-and-tours-website\node_modules\react-router\dist\production\index.js:9420:5)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at requestHandler (C:\projects\_pewvegas\pm-travels-and-tours-website\node_modules\react-router\dist\production\index.js:9206:18)
    at nodeHandler (C:\projects\_pewvegas\pm-travels-and-tours-website\node_modules\@react-router\dev\dist\vite.js:1967:30)
    at C:\projects\_pewvegas\pm-travels-and-tours-website\node_modules\@react-router\dev\dist\vite.js:1973:17

```

**Comment by KwaminaWhyte** [comment]
Yes 
```
{
username: "username",
email: "email"
}
```

**Comment by ASgmbv** [comment]
You need to return Response object

**Comment by sergiodxa** [comment]
Try to return `Response.json({ username: "username", email: "email" })`

While in UI routes you can return naked objects, in API routes you need to return a response, I recommend you to always return responses for consistency.

**Comment by Tom-DK** [comment]
FYI: people getting bugs using the [data()](https://api.reactrouter.com/v7/functions/react_router.data.html) util, from v7.1.5 this function works again.
