### ISSUE TITLE
"`useSubmit` must be used within a data router" for 3rd party libraries on node 22.12.0

### ISSUE THREAD

**Issue by brookslybrand** [remix-run/react-router#12475]
### I'm using React Router as a...

framework

### Reproduction

This is the same issue as #12399 and #12401. It specifically breaks if you're using the latest version of Node 22 (22.12)

I can't use StackBlitz since it doesn't let me set the Node version, so here we go:

**Use the latest node version**

Note: If I use v22.9.0, I do not get this error 🙃 

`nvm use v22.12.0`

**setup a new template**

`npx create-react-router@latest -y`

**Add `remix-hook-form`**

`npm i remix-hook-form`

**Call `useRemixForm`**

```tsx
// home.tsx

export default function Home() {
  const form = useRemixForm({});
  return <Welcome />;
}
```

### System Info

```shell
System:
    OS: macOS 15.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 93.73 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.12.0 - ~/.nvm/versions/node/v22.12.0/bin/node
    Yarn: 1.22.22 - ~/.nvm/versions/node/v20.17.0/bin/yarn
    npm: 10.9.0 - ~/.nvm/versions/node/v22.12.0/bin/npm
    pnpm: 9.7.1 - ~/.nvm/versions/node/v20.17.0/bin/pnpm
    bun: 1.1.0 - ~/.bun/bin/bun
  Browsers:
    Chrome: 130.0.6723.117
    Safari: 18.1
  npmPackages:
    @react-router/dev: 7.0.2 => 7.0.2 
    @react-router/node: 7.0.2 => 7.0.2 
    @react-router/serve: 7.0.2 => 7.0.2 
    react-router: 7.0.2 => 7.0.2 
    vite: ^5.4.11 => 5.4.11
```

### Used Package Manager

npm

### Expected Behavior

It should work (see #12437 for initial fix)

### Actual Behavior

It does not

**Comment by zackperdue** [comment]
What is the best way to get this to work? I tried npm and overrides and patch-package but I get this error:
```
ERROR: [plugin: vite:de
p-pre-bundle] Missing "./server" specifier in "react-router-dom"
```

**Comment by MaxLardenois** [comment]
> What is the best way to get this to work? I tried npm and overrides and patch-package but I get this error:
> 
> ```
> ERROR: [plugin: vite:de
> p-pre-bundle] Missing "./server" specifier in "react-router-dom"
> ```

It worked for by downgrading to Node v22.11.0

**Comment by zackperdue** [comment]
> > What is the best way to get this to work? I tried npm and overrides and patch-package but I get this error:
> > ```
> > ERROR: [plugin: vite:de
> > p-pre-bundle] Missing "./server" specifier in "react-router-dom"
> > ```
> 
> It worked for by downgrading to Node v22.11.0

I'm on v22.9.0

**Comment by MrAlex94** [comment]
FWIW, I am facing a similar issue using Bun 1.1.40 + Clerk as mentioned in issue #12399.

**Comment by brookslybrand** [comment]
> FWIW, I am facing a similar issue using Bun 1.1.40 + Clerk as mentioned in issue #12399.

@MrAlex94 I was not able to replicate this. Would you please list the steps or a link to a minimal reproduction?

**Comment by zackperdue** [comment]
I was able to get around this. Not exactly sure what fixed it, but I removed remix from the project and reinstalled fresh, then moved all my routes/business logic back in and it started working again.

**Comment by Gusteg** [comment]
The same issue occurs when you use React Router as a library together with the `useLocation` hook from a third-party library. 
```
  System:
    OS: macOS 14.5
    CPU: (10) arm64 Apple M2 Pro
    Memory: 64.06 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.9.0 - ~/.asdf/installs/nodejs/20.9.0/bin/node
    npm: 10.5.2 - ~/.asdf/plugins/nodejs/shims/npm
  Browsers:
    Chrome: 131.0.6778.204
    Safari: 17.5
  npmPackages:
    @react-router/dev: ^7.0.2 => 7.0.2 
    react-router: ^7.0.2 => 7.0.2 
    vite: ^5.0.11 => 5.4.11 
```

**Comment by MrGlox** [comment]
After a considerable amount of investigation and testing, I had to migrate my project to the v7 router in various stages.

You'll need to follow all the steps in this link: https://reactrouter.com/upgrading/remix

For a useLocation problem, you need to install the react-router-dom library, which is not a direct react-router dependency (after multiple tests on my project).

Hope this helps, I'm working on node v22.12.

All my project's code is here: https://github.com/MrGlox/remix-nest-boilerplate

**Comment by Gusteg** [comment]
> After a considerable amount of investigation and testing, I had to migrate my project to the v7 router in various stages.
> 
> You'll need to follow all the steps in this link: https://reactrouter.com/upgrading/remix
> 
> For a useLocation problem, you need to install the react-router-dom library, which is not a direct react-router dependency (after multiple tests on my project).
> 
> Hope this helps, I'm working on node v22.12.
> 
> All my project's code is here: https://github.com/MrGlox/remix-nest-boilerplate it's a monorepo so look at the /apps/web folder. I'll switch all my useForm from @conform-to/react to remix-hook-form soon, but for now check the `dashboard.account.subscription._index.tsx` file for the integration.

Thanks for sharing your findings. Unfortunately, I’ve already followed these steps, and the outcome hasn’t changed—the issue with useLocation still persists. It appears the migration doesn’t resolve the underlying problem in my case.
![Group 1](https://github.com/user-attachments/assets/d199601f-a915-46eb-988f-b60883c67e4c)

**Comment by MrAlex94** [comment]
@brookslybrand, here's a repro: https://github.com/MrAlex94/rr7-repro

Using Bun `1.1.40`:

```
Oops!

useNavigate() may be used only in the context of a <Router> component.

Error: useNavigate() may be used only in the context of a <Router> component.
    at invariant (/Users/akontos/Workspace/repro/node_modules/react-router/dist/development/index.js:327:11)
    at useNavigateUnstable (/Users/akontos/Workspace/repro/node_modules/react-router/dist/development/index.js:4263:3)
    at useNavigate (/Users/akontos/Workspace/repro/node_modules/react-router/dist/development/index.js:4260:46)
    at useAwaitableNavigate (file:///Users/akontos/Workspace/repro/node_modules/@clerk/react-router/src/client/useAwaitableNavigate.tsx:8:20)
    at ClerkProviderBase (file:///Users/akontos/Workspace/repro/node_modules/@clerk/react-router/src/client/ReactRouterClerkProvider.tsx:36:29)
    at Object.react-stack-bottom-frame (/Users/akontos/Workspace/repro/node_modules/react-dom/cjs/react-dom-server.edge.development.js:8798:18)
    at renderWithHooks (/Users/akontos/Workspace/repro/node_modules/react-dom/cjs/react-dom-server.edge.development.js:4722:19)
    at renderElement (/Users/akontos/Workspace/repro/node_modules/react-dom/cjs/react-dom-server.edge.development.js:5157:23)
    at retryNode (/Users/akontos/Workspace/repro/node_modules/react-dom/cjs/react-dom-server.edge.development.js:5805:22)
    at renderNodeDestructive (/Users/akontos/Workspace/repro/node_modules/react-dom/cjs/react-dom-server.edge.development.js:5631:11)
```

**Comment by MrGlox** [comment]
> > After a considerable amount of investigation and testing, I had to migrate my project to the v7 router in various stages.
> > You'll need to follow all the steps in this link: https://reactrouter.com/upgrading/remix
> > For a useLocation problem, you need to install the react-router-dom library, which is not a direct react-router dependency (after multiple tests on my project).
> > Hope this helps, I'm working on node v22.12.
> > All my project's code is here: https://github.com/MrGlox/remix-nest-boilerplate it's a monorepo so look at the /apps/web folder. I'll switch all my useForm from @conform-to/react to remix-hook-form soon, but for now check the `dashboard.account.subscription._index.tsx` file for the integration.
> 
> Thanks for sharing your findings. Unfortunately, I’ve already followed these steps, and the outcome hasn’t changed—the issue with useLocation still persists. It appears the migration doesn’t resolve the underlying problem in my case. ![Group 1](https://private-user-images.githubusercontent.com/53402500/397700461-d199601f-a915-46eb-988f-b60883c67e4c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ2OTg5ODUsIm5iZiI6MTczNDY5ODY4NSwicGF0aCI6Ii81MzQwMjUwMC8zOTc3MDA0NjEtZDE5OTYwMWYtYTkxNS00NmViLTk4OGYtYjYwODgzYzY3ZTRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIwVDEyNDQ0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkxMDUwZWQ1Yzc4ZTIwMWJiNDdkNDM1ZTkxOGZmZjQ3ZmZkNDM5MDhiNzQxNTU3OGU3YWQ3NGNmNjRmM2MxNTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.7Vp5oTVln1qU2rVfUsV7tLAtUpRmUUbchL5u2p55f-c)

Have you added a new routes.tsx file and updated remix() your vite.config.ts by reactRouter() ? Also added react-router.config.ts and updated entry.server with entry.client. The update / hydration part is really important because it change all the basic logic about routing in you project.

**Comment by MrGlox** [comment]
> @brookslybrand, here's a repro: https://github.com/MrAlex94/rr7-repro
> 
> Using Bun `1.1.40`:
> 
> ```
> Oops!
> 
> useNavigate() may be used only in the context of a <Router> component.
> 
> Error: useNavigate() may be used only in the context of a <Router> component.
>     at invariant (/Users/akontos/Workspace/repro/node_modules/react-router/dist/development/index.js:327:11)
>     at useNavigateUnstable (/Users/akontos/Workspace/repro/node_modules/react-router/dist/development/index.js:4263:3)
>     at useNavigate (/Users/akontos/Workspace/repro/node_modules/react-router/dist/development/index.js:4260:46)
>     at useAwaitableNavigate (file:///Users/akontos/Workspace/repro/node_modules/@clerk/react-router/src/client/useAwaitableNavigate.tsx:8:20)
>     at ClerkProviderBase (file:///Users/akontos/Workspace/repro/node_modules/@clerk/react-router/src/client/ReactRouterClerkProvider.tsx:36:29)
>     at Object.react-stack-bottom-frame (/Users/akontos/Workspace/repro/node_modules/react-dom/cjs/react-dom-server.edge.development.js:8798:18)
>     at renderWithHooks (/Users/akontos/Workspace/repro/node_modules/react-dom/cjs/react-dom-server.edge.development.js:4722:19)
>     at renderElement (/Users/akontos/Workspace/repro/node_modules/react-dom/cjs/react-dom-server.edge.development.js:5157:23)
>     at retryNode (/Users/akontos/Workspace/repro/node_modules/react-dom/cjs/react-dom-server.edge.development.js:5805:22)
>     at renderNodeDestructive (/Users/akontos/Workspace/repro/node_modules/react-dom/cjs/react-dom-server.edge.development.js:5631:11)
> ```

renderToReadableStream wasn't working for me, I had to replace it by renderToPipeableStream in my case. Maybe think also to add a entry.client.tsx mainly with the hydrateRoot part.

**Comment by brookslybrand** [comment]
@MrGlox at first glance that seems unrelated. If you're able to get @MrAlex94's reproduction working that would be appreciated in helping us diagnose the issue

**Comment by cemalokten** [comment]
Any update on this?

**Comment by brophdawg11** [comment]
Hey folks - can anyone confirm if the change in #12708 fixes your issue?  You should be able to just edit the `node_modules/react-router/package.json` file directly and then run your app again.  You may also need to delete any caches such as `node_modules/.vite` to get it to pick up on the change.

**Comment by wobsoriano** [comment]
> Hey folks - can anyone confirm if the change in #12708 fixes your issue? You should be able to just edit the `node_modules/react-router/package.json` file directly and then run your app again. You may also need to delete any caches such as `node_modules/.vite` to get it to pick up on the change.

It works on our side (Clerk React Router SDK) too! Tested with multiple versions from Node 20 to 22.13 🚀

**Comment by heivo** [comment]
> Hey folks - can anyone confirm if the change in #12708 fixes your issue? You should be able to just edit the `node_modules/react-router/package.json` file directly and then run your app again. You may also need to delete any caches such as `node_modules/.vite` to get it to pick up on the change.

same here, the fix solves the issue for me :+1:

**Comment by airjp73** [comment]
> Hey folks - can anyone confirm if the change in #12708 fixes your issue? You should be able to just edit the `node_modules/react-router/package.json` file directly and then run your app again. You may also need to delete any caches such as `node_modules/.vite` to get it to pick up on the change.

This fix works for me locally with the RVF issue.

**Comment by markdalgleish** [comment]
I've got a proposed fix for this in #12716.

I've published it as `v0.0.0-experimental-4d16b23b6` for anyone who wants to try it out.

**Comment by brookslybrand** [comment]
@markdalgleish nice! This definitely solves the repo I had

I did some testing with other reproductions, and it looks like [this one](https://github.com/airjp73/rvf/issues/410) now fails on Node 20 and earlier versions of Node 22 🫠

The instructions are pretty simple, and I've gone ahead and created a [reproduction on StackBlitz](https://stackblitz.com/edit/github-3pczvtze?file=package.json). The only problem with StackBlitz is it's still stuck on node 18, but I have confirmed it's the same issue that's happening on Node 20

**Comment by wobsoriano** [comment]
@markdalgleish can confirm that fixes our [issue](https://github.com/clerk/javascript/issues/4826) with our Clerk React Router SDK. Tried with Node v20, v22.11, v22.12, v22.13

**Comment by OriginalEXE** [comment]
@markdalgleish Unlike the "manual" solution from @brophdawg11, react-router override with an experimental version did not seem to have an effect, still had the same issue 🤔

**Comment by markdalgleish** [comment]
I've got a fix that works for both the original issue and https://github.com/airjp73/rvf/issues/410.

Turns out it's an issue with Vite not using the `module-sync` condition for SSR externals even though it's being used by Node. PR here: https://github.com/remix-run/react-router/pull/12729. This is why the issue only shows in dev, not the production build.

If you want to try it out, I've published another experimental release as `0.0.0-experimental-5509a3c42`.

**Comment by brookslybrand** [comment]
Awesome! Thank you so much @markdalgleish, this seems to solve all of the issues I have been able to reproduce including the [last one I provided (updated with new package)](https://stackblitz.com/edit/github-3pczvtze?file=package.json)

**Comment by OriginalEXE** [comment]
Unfortunately, the fix doesn't address the following conditions:
- custom remix/react-router server
- Node v22.12.0

Version 18.x (on Stackblitz) works. Link to a lightly modified Stackblitz by @brookslybrand : https://stackblitz.com/edit/github-3pczvtze-izn4h9ox?file=server.ts,package.json

Unfortunately there's no way to change Node.js version on Stackblitz

**Comment by brookslybrand** [comment]
Hmm, that's weird, thanks @OriginalEXE for pointing that out, I was able to reproduce.

This seems to be something specific to using `tsx`. I don't have an issue doing either of the following:

- Switch the `dev` command to `"dev": "node --experimental-strip-types ./server.ts"`
- Change `server.ts` to `server.js`

**Comment by raulfdm** [comment]
> I've got a fix that works for both the original issue and [airjp73/rvf#410](https://github.com/airjp73/rvf/issues/410).
> 
> Turns out it's an issue with Vite not using the `module-sync` condition for SSR externals even though it's being used by Node. PR here: #12729. This is why the issue only shows in dev, not the production build.
> 
> If you want to try it out, I've published another experimental release as `0.0.0-experimental-5509a3c42`.

Just came across this issue in the current env:

```
  Binaries:
    Node: 22.13.0 - ~/.volta/tools/image/node/22.13.0/bin/node
    Yarn: 1.22.0 - ~/.volta/tools/image/yarn/1.22.0/bin/yarn
    npm: 10.9.2 - ~/.volta/tools/image/node/22.13.0/bin/npm
    pnpm: 9.15.3 - ~/.volta/tools/image/pnpm/9.15.3/bin/pnpm
    bun: 1.1.43 - ~/.bun/bin/bun
  npmPackages:
    @react-router/dev: 7.1.1 => 7.1.1 
    @react-router/express: 7.1.1 => 7.1.1 
    @react-router/fs-routes: 7.1.1 => 7.1.1 
    @react-router/node: 7.1.1 => 7.1.1 
    react: catalog:react19 => 19.0.0 
    react-dom: catalog:react19 => 19.0.0 
    react-router: 7.1.1 => 7.1.1 
```
    
Can confirm that using `0.0.0-experimental-5509a3c42` fixed the problem. Waiting this to be released so I can finish the migration :)

**Comment by OriginalEXE** [comment]
> Hmm, that's weird, thanks [@OriginalEXE](https://github.com/OriginalEXE) for pointing that out, I was able to reproduce.
> 
> This seems to be something specific to using `tsx`. I don't have an issue doing either of the following:
> 
> * Switch the `dev` command to `"dev": "node --experimental-strip-types ./server.ts"`
> * Change `server.ts` to `server.js`

Interesting, thanks for debugging that. Sadly, my server is a bit complex so isolating it from my TS code is not possible. For now the fix by @brophdawg11 works for me locally in dev. For deployment I might have to figure something else out.

**Comment by acrognale** [comment]
I seem to be experiencing this issue still on the newly released react-router 7.1.2 when using Bun 1.1.43 still. I can also confirm that switching to node 22.13.0 does fix it.

**Comment by itsjavi** [comment]
With RR 7.1.1, I had this issue, but I cannot reproduce it anymore using Node 20.18.1 and RR 7.1.2.

**Comment by acelaya** [comment]
I still see the issue with react-router 7.1.2 when using node >=22.11.

The only solution that worked for me was https://github.com/remix-run/react-router/issues/12475#issuecomment-2578174224, but I see that was not merged in the end.

**Comment by raulfdm** [comment]
Can confirm that `7.1.2` fixed the issue

```
Binaries:
    Node: 22.13.0 - ~/.volta/tools/image/node/22.13.0/bin/node
    Yarn: 1.22.0 - ~/.volta/tools/image/yarn/1.22.0/bin/yarn
    npm: 10.9.2 - ~/.volta/tools/image/node/22.13.0/bin/npm
    pnpm: 9.15.3 - ~/.volta/tools/image/pnpm/9.15.3/bin/pnpm
    bun: 1.1.43 - ~/.bun/bin/bun
  npmPackages:
    @react-router/dev: 7.1.2 => 7.1.2 
    @react-router/express: 7.1.2 => 7.1.2 
    @react-router/fs-routes: 7.1.2 => 7.1.2 
    @react-router/node: 7.1.2 => 7.1.2 
    react: catalog:react18 => 18.3.1 
    react-dom: catalog:react18 => 18.3.1 
    react-router: 7.1.2 => 7.1.2 
```

**Comment by acelaya** [comment]
I see this was closed, but it's still reproducible with latest version when running with vitest (which bundles with vite), if your project depends on something which in turn has a peer dependency on react-router.

Imports in the root project end up with a different router version than imports in the dependency (I'm assuming, based on the discussion here).

I'll try to put together a minimum reproduction and open another issue focused on that specific combination, as the fix that landed in 7.1.2 seems to have fixed the error for other combinations.

**Comment by acelaya** [comment]
> I see this was closed, but it's still reproducible with latest version when running with vitest (which bundles with vite), if your project depends on something which in turn has a peer dependency on react-router.
> 
> Imports in the root project end up with a different router version than imports in the dependency (I'm assuming, based on the discussion here).
> 
> I'll try to put together a minimum reproduction and open another issue focused on that specific combination, as the fix that landed in 7.1.2 seems to have fixed the error for other combinations.

I created a new issue, with the steps to reproduce for this particular scenario https://github.com/remix-run/react-router/issues/12785

**Comment by Vgbire** [comment]
> The same issue occurs when you use React Router as a library together with the `useLocation` hook from a third-party library.
> 
> ```
>   System:
>     OS: macOS 14.5
>     CPU: (10) arm64 Apple M2 Pro
>     Memory: 64.06 MB / 32.00 GB
>     Shell: 5.9 - /bin/zsh
>   Binaries:
>     Node: 20.9.0 - ~/.asdf/installs/nodejs/20.9.0/bin/node
>     npm: 10.5.2 - ~/.asdf/plugins/nodejs/shims/npm
>   Browsers:
>     Chrome: 131.0.6778.204
>     Safari: 17.5
>   npmPackages:
>     @react-router/dev: ^7.0.2 => 7.0.2 
>     react-router: ^7.0.2 => 7.0.2 
>     vite: ^5.0.11 => 5.4.11 
> ```

I have the same problem, how can I solve it

**Comment by angelangelov88** [comment]
I had the same issue when I upgraded to React 19. I'm using React with Vite and node version 23.0.0. Fixed it by upgrading react-router-dom to latest (v7.2.0)

**Comment by itsjavi** [comment]
what it seems to work for me is to enable optimizeDeps in the `react-router.config.ts` file:

```tsx
export default {
// ...
 future: {
    unstable_optimizeDeps: true,
  }
}
```

**Comment by haines** [comment]
I'm still seeing `useRouteLoaderData must be used within a data router` with react-router@7.2.0 and @rvf/react-router@7.0.2, only when running in the Vite dev server, only on routes that use @rvf/react-router.

Removing the `module-sync` exports (as per https://github.com/remix-run/react-router/pull/12708) fixes the issue for me.

**Comment by g-wozniak** [comment]
Got the issue with:
```
    "@clerk/react-router": "^1.1.6",
    "react": "^19.0.0",
    "react-dom": "^19.0.0",
    "react-router-dom": "^7.4.0",
```

when implementing as:
```
// Define routes
const router = createBrowserRouter([
   {path: '/', element: <App/>},
   {path: '/dashboard', element: <ProtectedRoute><Dashboard/></ProtectedRoute>}
])

createRoot(document.getElementById('root')!).render(
   <React.StrictMode>
      <ClerkProvider publishableKey={process.env.CLERK_PUBLISHABLE_KEY}>
         <RouterProvider router={router}/>
      </ClerkProvider>
   </React.StrictMode>
)
```
