### ISSUE TITLE
Inline `Route` type import fails build and dev

### ISSUE THREAD

**Issue by wking-io** [remix-run/react-router#12503]
### I'm using React Router as a...

framework

### Reproduction

https://github.com/wking-io/no-inline-types

### System Info

```shell
System:
    OS: macOS 14.6.1
    CPU: (12) arm64 Apple M2 Pro
    Memory: 634.58 MB / 32.00 GB
    Shell: 3.6.1 - /opt/homebrew/bin/fish
  Binaries:
    Node: 22.12.0 - ~/.asdf/installs/nodejs/22.12.0/bin/node
    npm: 10.9.0 - ~/.asdf/plugins/nodejs/shims/npm
  Browsers:
    Chrome: 131.0.6778.109
    Edge: 131.0.2903.86
    Safari: 17.6
  npmPackages:
    @react-router/dev: ^7.0.2 => 7.0.2
    @react-router/node: ^7.0.2 => 7.0.2
    @react-router/serve: ^7.0.2 => 7.0.2
    react-router: ^7.0.2 => 7.0.2
    vite: ^5.4.11 => 5.4.11
```

### Used Package Manager

npm

### Expected Behavior

I would expect the import to "just work" whether the import is `import type { Route } from './+types/root'` or `import { type Route } from './+type'`

### Actual Behavior

The build fails with the following message:

```
Could not resolve "./+types/root" from "app/root.tsx"
file: /Users/wking/Developer/projects/no-inline-types/app/root.tsx
    at getRollupError (file:///Users/wking/Developer/projects/no-inline-types/node_modules/rollup/dist/es/shared/parseAst.js:396:41)
    at error (file:///Users/wking/Developer/projects/no-inline-types/node_modules/rollup/dist/es/shared/parseAst.js:392:42)
    at ModuleLoader.handleInvalidResolvedId (file:///Users/wking/Developer/projects/no-inline-types/node_modules/rollup/dist/es/shared/node-entry.js:20088:24)
    at file:///Users/wking/Developer/projects/no-inline-types/node_modules/rollup/dist/es/shared/node-entry.js:20048:26 {
  code: 'UNRESOLVED_IMPORT',
  exporter: './+types/root',
  id: '/Users/wking/Developer/projects/no-inline-types/app/root.tsx',
  watchFiles: [
    '/Users/wking/Developer/projects/no-inline-types/app/routes/home.tsx',
    '/Users/wking/Developer/projects/no-inline-types/app/root.tsx',
    '/Users/wking/Developer/projects/no-inline-types/node_modules/@react-router/dev/dist/config/defaults/entry.client.tsx',
    '/Users/wking/Developer/projects/no-inline-types/package.json',
    '/Users/wking/Developer/projects/no-inline-types/node_modules/react/index.js',
    '/Users/wking/Developer/projects/no-inline-types/node_modules/react/jsx-runtime.js',
    '/Users/wking/Developer/projects/no-inline-types/node_modules/react-router/dist/development/dom-export.mjs',
    '/Users/wking/Developer/projects/no-inline-types/node_modules/react-dom/client.js',
    'package.json',
    '/Users/wking/Developer/projects/no-inline-types/node_modules/react/cjs/react.production.min.js',
    '/Users/wking/Developer/projects/no-inline-types/node_modules/react/cjs/react-jsx-runtime.production.min.js',
    '/Users/wking/Developer/projects/no-inline-types/node_modules/react-dom/index.js',
    '/Users/wking/Developer/projects/no-inline-types/app/welcome/welcome.tsx',
    '/Users/wking/Developer/projects/no-inline-types/node_modules/react-router/dist/development/chunk-D52XG6IA.mjs',
    '/Users/wking/Developer/projects/no-inline-types/node_modules/react-router/dist/development/index.mjs',
    '/Users/wking/Developer/projects/no-inline-types/app/app.css',
    '/Users/wking/Developer/projects/no-inline-types/node_modules/react-dom/cjs/react-dom.production.min.js',
    '/Users/wking/Developer/projects/no-inline-types/node_modules/scheduler/index.js'
  ]
}
```

**Comment by brookslybrand** [comment]
I think this is due to `"verbatimModuleSyntax": true,` in `tsconfig.json`. So not technically a React Router bug, but not something that's very obvious without linting (which we don't have automatically in the templates)

**Comment by Cavdy** [comment]
I think you need to generate the types

I followed the instructions here to fix mine https://reactrouter.com/how-to/route-module-type-safety

**Comment by wking-io** [comment]
Okay found it!

![image](https://github.com/user-attachments/assets/fc4ae4b6-c6f2-467a-afaf-77d582684b5a)

**Comment by Hyeong-jin** [comment]
[After creating the project, run the following:](https://reactrouter.com/explanation/type-safety)

"npm run typecheck"

**Comment by pcattori** [comment]
Closing as this is expected behavior in TS. We've also added `verbatimModuleSyntax: true` in our official templates so that (most) editors autoimport with the correct syntax.
