### ISSUE TITLE
Basic framework "Installation Instructions" with run npm dev HMR throws 404s on any change

### ISSUE THREAD

**Issue by tdbrian** [remix-run/react-router#12554]
### I'm using React Router as a...

framework

### Reproduction

1. Run `npx create-react-router@latest my-react-router-app`
2. Run cd my-react-router-app
3. Run npm i
4. Run npm run dev
5. Go to http://localhost:5173/
6. Make any change or reload the page

Initial load works fine but any subsequent code changes or reloading the page results in all assets getting a 404.

![rr-1](https://github.com/user-attachments/assets/3bd7e597-f479-465c-b940-3cbc7deb9bc7)

Console output:
```
> dev
> react-router dev

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
  ➜  press h + enter to show help
Error: No route matches URL "/@react-refresh"
    at getInternalRouterError (/Users/thomasbrian/Projects/CrateAndBarrel/my-react-router-app/node_modules/react-router/dist/development/index.js:3908:5)
    at Object.query (/Users/thomasbrian/Projects/CrateAndBarrel/my-react-router-app/node_modules/react-router/dist/development/index.js:2744:19)
    at handleDocumentRequest (/Users/thomasbrian/Projects/CrateAndBarrel/my-react-router-app/node_modules/react-router/dist/development/index.js:9300:35)
    at requestHandler (/Users/thomasbrian/Projects/CrateAndBarrel/my-react-router-app/node_modules/react-router/dist/development/index.js:9217:24)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
    at nodeHandler (/Users/thomasbrian/Projects/CrateAndBarrel/my-react-router-app/node_modules/@react-router/dev/dist/vite.js:1969:30)
    at /Users/thomasbrian/Projects/CrateAndBarrel/my-react-router-app/node_modules/@react-router/dev/dist/vite.js:1975:17
Error: No route matches URL "/@vite-plugin-pwa/pwa-entry-point-loaded"
    at getInternalRouterError (/Users/thomasbrian/Projects/CrateAndBarrel/my-react-router-app/node_modules/react-router/dist/development/index.js:3908:5)
    at Object.query (/Users/thomasbrian/Projects/CrateAndBarrel/my-react-router-app/node_modules/react-router/dist/development/index.js:2744:19)
    at handleDocumentRequest (/Users/thomasbrian/Projects/CrateAndBarrel/my-react-router-app/node_modules/react-router/dist/development/index.js:9300:35)
    at requestHandler (/Users/thomasbrian/Projects/CrateAndBarrel/my-react-router-app/node_modules/react-router/dist/development/index.js:9217:24)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
    at nodeHandler (/Users/thomasbrian/Projects/CrateAndBarrel/my-react-router-app/node_modules/@react-router/dev/dist/vite.js:1969:30)
    at /Users/thomasbrian/Projects/CrateAndBarrel/my-react-router-app/node_modules/@react-router/dev/dist/vite.js:1975:17
No routes matched location "/@react-refresh"
No routes matched location "/@vite-plugin-pwa/pwa-entry-point-loaded"
```

### System Info

```shell
System:
    OS: macOS 14.6.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 208.38 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.11.0 - /usr/local/bin/node
    Yarn: 3.2.4 - /usr/local/bin/yarn
    npm: 10.9.1 - /usr/local/bin/npm
    pnpm: 9.0.1 - /usr/local/bin/pnpm
    bun: 1.0.1 - /usr/local/bin/bun
    Watchman: 2024.05.06.00 - /usr/local/bin/watchman
  Browsers:
    Chrome: 131.0.6778.140
    Safari: 17.6
  npmPackages:
    @react-router/dev: ^7.0.2 => 7.0.2
    @react-router/node: ^7.0.2 => 7.0.2
    @react-router/serve: ^7.0.2 => 7.0.2
    react-router: ^7.0.2 => 7.0.2
    vite: ^5.4.11 => 5.4.11
```

### Used Package Manager

npm

### Expected Behavior

HMR should work and show the app.

### Actual Behavior

All assets via HMR are returned as 404 after initial page load running dev.

**Comment by timdorr** [comment]
I'm not seeing this at all after running those exact commands. My best guess is you have something else running on that port and you're loading the wrong server, or there is some sort of firewall blockage or browser extension getting in the way.
