### ISSUE TITLE
#12578 breaks command `react-router dev --any-param`

### ISSUE THREAD

**Issue by Master-Hash** [remix-run/react-router#12606]
### I'm using React Router as a...

framework

### Reproduction

1. Define script in packages.json: `"dev": "react-router dev --host",`
2. run `pnpm run dev`

### System Info

```shell
System:
    OS: Windows 11 10.0.26100
    CPU: (16) x64 AMD Ryzen 7 6800U with Radeon Graphics
    Memory: 2.19 GB / 15.24 GB
  Binaries:
    Node: 23.4.0 - C:\Program Files\nodejs\node.EXE
    pnpm: 9.15.1 - C:\Program Files\nodejs\pnpm.CMD
    bun: 1.1.29 - C:\Program Files\WinGet\Links\bun.EXE
  Browsers: {}
  npmPackages:
    @react-router/dev: ^7.1.0 => 7.1.0
    @react-router/fs-routes: ^7.1.0 => 7.1.0
    @react-router/node: ^7.1.0 => 7.1.0
    @react-router/serve: ^7.1.0 => 7.1.0
    react-router: ^7.1.0 => 7.1.0
    vite: ^6.0.5 => 6.0.5
```

### Used Package Manager

pnpm

### Expected Behavior

Just works

### Actual Behavior

```ts
> react-router dev --host

C:\Users\hash\Desktop\xxxx\node_modules\.pnpm\arg@5.0.2\node_modules\arg\index.js:132
                                                throw new ArgError(
                                                ^

ArgError: unknown or unexpected option: --host
    at arg (C:\Users\hash\Desktop\taup\node_modules\.pnpm\arg@5.0.2\node_modules\arg\index.js:132:13)
    at Object.<anonymous> (C:\Users\hash\Desktop\taup\node_modules\.pnpm\@react-router+dev@7.1.0_@react-router+serve@7.1.0_react-router@7.1.0_react-dom@19.0.0_react@1_aa57s26fwl7ukaaplgz4hwj76m\node_modules\@react-router\dev\bin.js:8:12)   
    at Module._compile (node:internal/modules/cjs/loader:1566:14)
    at Object..js (node:internal/modules/cjs/loader:1718:10)
    at Module.load (node:internal/modules/cjs/loader:1305:32)
    at Function._load (node:internal/modules/cjs/loader:1119:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:220:24)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:151:5)
    at node:internal/main/run_main_module:33:47 {
  code: 'ARG_UNKNOWN_OPTION'
}
```

**Comment by PhilDL** [comment]
#12578 is indeed the issue, you can fixed it locally by patching the @react-router/dev package with the following changes.

```diff
diff --git a/bin.js b/bin.js
index 88866010646f42058bd8daf29896fb6be55d4eb7..0373bf96f7c42f5460dc2e9fea394e9a7e947e06 100755
--- a/bin.js
+++ b/bin.js
@@ -5,7 +5,7 @@ let arg = require("arg");
 // default `NODE_ENV` so React loads the proper version in it's CJS entry script.
 // We have to do this before importing `run.ts` since that is what imports
 // `react` (indirectly via `react-router`)
-let args = arg({}, { argv: process.argv.slice(2) });
+let args = arg({}, { argv: process.argv.slice(2), stopAtPositional: true });
 if (args._[0] === "dev") {
   process.env.NODE_ENV = process.env.NODE_ENV ?? "development";
 } else {
```

Adding `stopPositional: true` to the `arg` function (that was called with no positional args `{}`) will make it bypass optional positional args often used like `build --sourcemapClient --sourcemapServer`. So the function will not crash anymore.

**Comment by jesse996** [comment]
same, `react router dev --mode dev` not work

**Comment by timdorr** [comment]
You can use `7.1.1-pre.0` on npm for now. That is the only change in that version. I don't know if I have access to finish the full release here, so I'm leaving it as a prerelease for now.

**Comment by IsaacCloos** [comment]
I believe this issue should remain open. I'm still getting the following error on windows 11

```
npm ls -g
+-- @react-router/dev@7.1.1
`-- npm@11.0.0

 npx react-router -h
...\AppData\Roaming\npm\node_modules\@react-router\dev\node_modules\arg\index.js:132
                                                throw new ArgError(
                                                ^

ArgError: unknown or unexpected option: -h
 ... {
  code: 'ARG_UNKNOWN_OPTION'
}

Node.js v22.12.0
```

**Comment by PhilDL** [comment]
This specific issue with the `dev` option is fixed and should remained closed, but the other one #12627 about the command with no option (dev | build | etc) should probably be reopened yes.

**Comment by brophdawg11** [comment]
This should be resolved by #12925 and available in the next release
