### ISSUE TITLE
Fails to resolve @prisma/client with Vite v6

### ISSUE THREAD

**Issue by silvenon** [remix-run/react-router#12610]
### I'm using React Router as a...

framework

### Reproduction

https://github.com/silvenon/repro/tree/react-router-v7-vite-v6-resolve-prisma-client

Clone the repository:

```sh
# if you have GitHub CLI installed run
gh repo clone silvenon/repro -- --branch react-router-v7-vite-v6-resolve-prisma-client
cd repro
# otherwise run
git clone https://github.com/silvenon/repro.git
cd repro
git switch react-router-v7-vite-v6-resolve-prisma-client
```

Install dependencies and set up Prisma:

```
npm run setup
```

The issue is present both in development and in build:

```
npm run dev
```
```
npm run build
```

### System Info

```shell
System:
    OS: macOS 15.2
    CPU: (8) arm64 Apple M1 Pro
    Memory: 297.69 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.18.1 - ~/.n/bin/node
    Yarn: 1.22.22 - /opt/homebrew/bin/yarn
    npm: 10.8.2 - ~/.n/bin/npm
    pnpm: 9.15.1 - /opt/homebrew/bin/pnpm
    bun: 1.1.29 - ~/.bun/bin/bun
  Browsers:
    Chrome: 131.0.6778.205
    Edge: 131.0.2903.112
    Safari: 18.2
  npmPackages:
    @react-router/dev: ^7.1.0 => 7.1.0 
    @react-router/node: ^7.1.0 => 7.1.0 
    @react-router/serve: ^7.1.0 => 7.1.0 
    react-router: ^7.1.0 => 7.1.0 
    vite: ^6.0.5 => 6.0.5
```

### Used Package Manager

npm

### Expected Behavior

Expected to be able to upgrade to React Router v7.1.0 and to Vite v6, and have my app working as usual.

### Actual Behavior

With Vite v6 it's failing to resolve `@prisma/client` both in dev and build.

Before v7.1.0 I had the same problem when I tried upgrading Vite to v6, so I was wondering what went wrong, but then I saw that you were still working on Vite v6 support so I assumed it was because of that, however unfortunately the problem remained.

I tried using Environment API to import `@prisma/client` in Vite v6 SSR without React Router involved, and it worked, so I think this has something to do with how React Router is using Vite.

```
[plugin:vite:import-analysis] Failed to resolve entry for package "@prisma/client". The package may have incorrect main/module/exports specified in its package.json: No known conditions for "." specifier in "@prisma/client" package
```

**Comment by timdorr** [comment]
This is a Prisma issue with packaging and Vite handles it, not an issue with React Router. You can work around this by importing the default explicitly or importing as a default-less module: https://github.com/prisma/prisma/issues/6491#issuecomment-847141591

**Comment by silvenon** [comment]
Are you sure that this is a current Prisma issue? The linked issue is 3 years old, and none of the solutions there are working for me.

Prisma packaging has changed a lot since this issue, it used to be CJS-only then, now it's dual publish and supports all kinds of environments. And with the latest version [publint doesn't report significant problems](https://publint.dev/@prisma/client@6.1.0).

Also, as I described in my bug report, I'm _not_ running into this issue in Vite v6 alone: https://github.com/silvenon/repro/tree/vite-v6-prisma-client, nor in Vite v5 + React Router. This is why I suspect that there is something that React Router does that doesn't work well with how Vite v6 resolves Prisma.

Note that In my example with only Vite v6 + Prisma I'm using Environment API, maybe this makes some kind of a difference in resolution 🤷‍♂️

**Comment by silvenon** [comment]
I mean, I can understand the strong suspicion towards Prisma, I really wanted to find some kind of a problem there because if there was a problem with how React Router loads modules wouldn't other modules be failing to resolve as well? Why just Prisma…

I guess I need to go dig deeper, I would just appreciate some pointers regarding which Vite API for loading modules I need to look into for this. Just regular `ssrLoadModule` or something more complicated?

**Comment by luka-cfi** [comment]
> This is a Prisma issue with packaging and Vite handles it, not an issue with React Router. You can work around this by importing the default explicitly or importing as a default-less module: [prisma/prisma#6491 (comment)](https://github.com/prisma/prisma/issues/6491#issuecomment-847141591)

none of this solution works for dev run 

```
build:{
 rollupOptions: {
      external: ["@prisma/client"],
    },
    }
    ```
    
    this works for prod build only

**Comment by luka-cfi** [comment]
solution if anyone looks for it is to add 

```
output          = "../node_modules/randomdbname"
```
in schema.prisma then run npx prisma generate 

and in vite config 

```
ssr: {
    optimizeDeps: {
      include: ["randomdbname"],
    },
  },
```
  
replace randomdbname with whatever

**Comment by silvenon** [comment]
So by default this?

```js
ssr: {
  optimizeDeps: {
    include: ["./node_modules/.prisma/client"],
  },
},
```

Unfortunately it didn't work for me either.

Just in case I also tried generating to a non-dot path using the recommended `output`, but still resolution gets stuck at `@prisma/client`.

**Comment by lukasa1993** [comment]
> So by default this?
> 
> ```js
> ssr: {
>   optimizeDeps: {
>     include: ["./node_modules/.prisma/client"],
>   },
> },
> ```
> 
> Unfortunately it didn't work for me either. In my repro could you tell me which steps exactly I need to do to get it working?
> 
> Just in case I also tried generating to a non-dot path using the recommended `output`, but still resolution gets stuck at `@prisma/client`.

that doesn't work since vite6 has some issue with path starting . so my solution bypasses that

**Comment by silvenon** [comment]
Stripping away `./node_modules/` doesn't work for me either, so unless you can provide a working fork of my repro, let's not prolong this issue any longer than it needs to be.

Maybe for some reason it works for you, but I can't know the specifics of your setup without a working demo.

**Comment by lukasa1993** [comment]
> Stripping away `./node_modules/` doesn't work for me either, so unless you can provide a working fork of my repro, let's not prolong this issue any longer than it needs to be.
> 
> Maybe for some reason it works for you, but I can't know the specifics of your setup without a working demo.

https://github.com/silvenon/repro/pull/1

**Comment by silvenon** [comment]
But there's no bug with Vite v6 + Prisma alone, only when React Router is involved, so this is the repro that needs to be fixed: https://github.com/silvenon/repro/tree/react-router-v7-vite-v6-resolve-prisma-client

**Comment by silvenon** [comment]
My apologies, the same fix would've worked for the React Router repro. When I was trying it out I forgot to update my imports. Sorry!

This workaround seems to solve the issue. I would've still liked to know what caused it so that I can properly report it to the appropriate project, but it's difficult to tell.

**Comment by lukasa1993** [comment]
> My apologies, the same fix would've worked for the React Router repro. I didn't think I also needed to update all of my imports, I thought that the `@prisma/client` imports can stay.
> 
> This workaround seems to solve the issue. I would've still liked to know what caused it so that I can properly report it to the appropriate project, but it's difficult to know where to look.
> 
> Thanks for your help!

something with vite aliases and '.' handling in path

**Comment by sapphi-red** [comment]
My guess is that this breaking change in Vite v6 is affecting your case.
https://vite.dev/guide/migration.html#default-value-for-resolve-conditions
It seems RR sets `conditions: []` here
https://github.com/remix-run/react-router/blob/6a5b4f22b6b989ace38547e749e8602065f820f4/packages/react-router-dev/vite/plugin.ts#L807
https://github.com/remix-run/react-router/blob/6a5b4f22b6b989ace38547e749e8602065f820f4/packages/react-router-dev/vite/plugin.ts#L856
and that removes all default conditions.

**Comment by silvenon** [comment]
Wow, very nice catch, thank you so much! ❤️

Now `@prisma/client` is resolving, but SSRCompatModuleRunner fails to evaluate `@prisma/client`, I guess because it's CJS-only? (prisma/prisma#21858) However, certainly there are other dependencies that are CJS as well, so there's something else going on.

Now I know where to look 💪

@sapphi-red will you do the honors of submitting the fix for `resolve.conditions` to React Router?

```
8:44:38 AM [vite] (ssr) Error when evaluating SSR module virtual:react-router/server-build:
|- ReferenceError: module is not defined
    at eval (/Users/silvenon/Code/epi/node_modules/@prisma/client/default.js:3:14)
    at ESModulesEvaluator.runInlinedModule (file:///Users/silvenon/Code/epi/node_modules/vite/dist/node/module-runner.js:1061:6)
    at SSRCompatModuleRunner.directRequest (file:///Users/silvenon/Code/epi/node_modules/vite/dist/node/module-runner.js:1279:82)
    at SSRCompatModuleRunner.directRequest (file:///Users/silvenon/Code/epi/node_modules/vite/dist/node/chunks/dep-BZMjGe_U.js:30785:35)
    at SSRCompatModuleRunner.cachedRequest (file:///Users/silvenon/Code/epi/node_modules/vite/dist/node/module-runner.js:1173:28)
    at request (file:///Users/silvenon/Code/epi/node_modules/vite/dist/node/module-runner.js:1223:79)
    at eval (/Users/silvenon/Code/epi/app/db.server.ts:3:44)
    at ESModulesEvaluator.runInlinedModule (file:///Users/silvenon/Code/epi/node_modules/vite/dist/node/module-runner.js:1053:5)
    at SSRCompatModuleRunner.directRequest (file:///Users/silvenon/Code/epi/node_modules/vite/dist/node/module-runner.js:1279:61)
    at SSRCompatModuleRunner.directRequest (file:///Users/silvenon/Code/epi/node_modules/vite/dist/node/chunks/dep-BZMjGe_U.js:30785:23)
```

**Comment by silvenon** [comment]
@timdorr considering that my suspicions were true that the transition to Vite v6 is incomplete, could you reopen the bug report for now? At least until `resolve.conditions` fix is merged, the subsequent problem I can submit in a separate report.

**Comment by sapphi-red** [comment]
> will you do the honors of submitting the fix for `resolve.conditions` to React Router?

It'll take some time to make a PR for me so feel free to create one instead of me🙂

**Comment by JasonColeyNZ** [comment]
I managed to get prisma working with Vite6 using...

import { remember } from "@epic-web/remember"
import { PrismaClient } from "@prisma/client/index.js"
export * from "@prisma/client/index.js"
export const prisma = remember("prisma", () => new PrismaClient())

This is my db.server.ts file and import everything from this file.

**Comment by IsaacCloos** [comment]
Perhaps in the near future Prisma will update to address this issue. In the meantime, I've found that changing my `db.server.ts` import of `@prisma/client` to `@prisma/client/index.js` seems to get it working again.

**Comment by silvenon** [comment]
Indeed, thanks for the workaround, `@prisma/client/index.js` is what `@prisma/client` import should resolve to. Maybe adding an alias in Vite configuration could work as well, that way we get to keep the imports:

```
resolve: {
  alias: {
  }
}
```

**Comment by silvenon** [comment]
Just like in the PR, the final missing ingredient was configuring `ssr.resolve.externalConditions` to `defaultServerConditions` as well, so adding that to sapphi's suggestion https://github.com/remix-run/react-router/issues/12610#issuecomment-2558799620 completes the workaround, so there is no need for importing `@prisma/client/index` or anything like that. At least not in my project.

**Comment by chanpod** [comment]
Can confirm, not able to deploy to vercel with prisma and vite 5 or 6. Lots of resolution issues. Tried every combination of "solutions" i've around around the web. Nothing is working :( 

This is in the home component for the vercel template project. It deploys fine without the prisma import. I've tried regular prisma imports, this workaround plugin, the  solution from jasoncoley, nothing is working. 

```
import { reactRouter } from "@react-router/dev/vite";
import autoprefixer from "autoprefixer";
import tailwindcss from "tailwindcss";
import { defineConfig } from "vite";
import tsconfigPaths from "vite-tsconfig-paths";
import { defaultClientConditions, defaultServerConditions } from "vite";

// Add this plugin to your Vite config
const prismaFixPlugin = {
  name: "prisma-fix",
  enforce: "post",
  config() {
    return {
      resolve: {
        conditions: [...defaultClientConditions],
      },
      ssr: {
        resolve: {
          conditions: [...defaultServerConditions],
          externalConditions: [...defaultServerConditions],
        },
      },
    };
  },
};

export default defineConfig(({ isSsrBuild, command }) => ({
  resolve: {
    alias: {
      "@prisma/client": "@prisma/client/index.js",
    },
  },
  build: {
    rollupOptions: isSsrBuild
      ? {
          input: "./server/app.ts",
        }
      : undefined,
  },
  css: {
    postcss: {
      plugins: [tailwindcss, autoprefixer],
    },
  },
  ssr: {
    noExternal: command === "build" ? true : undefined,
  },
  plugins: [prismaFixPlugin, reactRouter(), tsconfigPaths()],
}));
```

**Comment by chanpod** [comment]
https://github.com/chanpod/reactrouter7wprisma

here's a basic repository for testing. This fails to run on vercel unless you remove the prisma import.

**Comment by silvenon** [comment]
I think you're having additional issues because you're also _bundling_ the SSR build, which has a separate host of issues unrelated to React Router https://github.com/vitejs/vite/issues/19036#issuecomment-2567056409.

First and foremost due to `@prisma/client` importing `.prisma/client`, which is an unsupported package name in Vite, but even after clearing that hurdle, due to Prisma being CJS-only, you'll end up with `__dirname` and `__filename` in your bundle. Seems like Vite's CJS interoperability doesn't go as far taking care of those. And as a cherry on top, Prisma's library also does `eval("__dirname")`, I don't know why.

So I recommend generating the Prisma client as `@prisma/client-generated` rather than `.prisma/client` via `output = "../node_modules/@prisma/client-generated"` in the schema and following the rest of the steps, including creating another custom plugin to apply the ESM adaptations to Prisma.

I don't know if all of those fixes will indeed work in the runtime, but you can continue from where we left off 😄

If you don't want to go through all that you can try out Drizzle. I haven't tried it yet myself, but Prisma doesn't seem to be upgrading to ESM any time soon despite the PR from the core team member, so I would choose Drizzle for my next project instead of applying fragile ESM adaptations to Prisma.

And as for your alias to `@prisma/client/index.js` you can either drop it because it turned out not to be needed with the full workaround, and you're not going to be importing `@prisma/client` now anyway, but `@prisma/client-generated`, or you can alias `@prisma/client` to `@prisma/client-generated`, however you want.

**Comment by punkpeye** [comment]
For anyone coming across this because of charts, this fix (mentioned earlier in the thread) fixes it:

```ts
// Need to fix errors like:
// Uncaught TypeError: Cannot destructure property '__extends' of 'import_tslib.default' as it is undefined.
// @see https://github.com/remix-run/react-router/issues/12610
plugins.push({
  config() {
    return {
      resolve: {
        conditions: [...defaultClientConditions],
      },
      ssr: {
        resolve: {
          conditions: [...defaultServerConditions],
          externalConditions: [...defaultServerConditions],
        },
      },
    };
  },
  enforce: 'post',
  name: 'tslib-fix',
});
```
