### ISSUE TITLE
RR7 lazyRouteDiscover (Fog of War) opt-out

### ISSUE THREAD

**Issue by mikkpokk** [remix-run/react-router#12656]
### Missing information how to disable lazy route discover (also known as Fog of War) feature. 

In my case, it causes unnecessary overhead on application which renders thousands of links (filters and products) but there are only 7 RR routes in total. Would love to disable the feature.

**Comment by s-abstract** [comment]
Same here. Would love to see a way to opt out the feature or configure it.

**Comment by david-szabo97** [comment]
We need more control over Fog of War. I noticed the same issue, we have a search results page where each result is a different link. React Router fetches a manifest for all the links, but it's just a single route with parameters. It would be great to have some way to exclude links from discovery and just use whatever is already loaded.

The initial manifest only contains the matched routes. Therefore a manifest is always fetched on page load. We should have an (optional) option to eagerly load those as well.

**Comment by mikkpokk** [comment]
I digged a bit deeper in source code and it seems there is only 1 solution - use `discover={'none'}` property value on NavLink / Link component on most of the links and let FOW to do it's thing on single route link only.

For an example

``javascript
// Main navigation
<Link to={'/'}>Home</Link>
<Link to={'/products'}>Products</Link>
<Link to={'/login'}>Login</Link>
<Link to={'/register'}>Register</Link>
...
// Filters
<Link to={'/products?color[]=blue'} discover={'none'}>Blue</Link>
<Link to={'/products?color[]=red'} discover={'none'}>Red</Link>

// Pagination
<Link to={'/products?page=2'} discover={'none'}>2</Link>

// Products
{items.map((item, key) => (
    <Link to={`/products/${item.slug}`} discover={'none'}>
        <ProductCard item={item} discover={key === 0 ? 'render' : 'none'} />
    </Link>
))}
``

**However, it gets really messy and hard to maintain such a mayhem project in the future. Let's hope to hear authors thoughts soon.**

**Comment by miguelvictor** [comment]
I agree, adding discover="none" to all `<Links />` is so hard. There should be a global setting to disable lazyRouteDiscovery.

**Comment by skyqrose** [comment]
+1. In my case it's causing my tests to fail during my v7 upgrade, because my assertions didn't expect the new `data-discover="true"` on every link.

<details>
<summary>Example of a typical test failure in a jest snapshot test</summary>

```
FAIL  tests/components/myComponent.test.tsx
  ● renders

    expect(received).toMatchSnapshot()

    Snapshot name: `renders 1`

    - Snapshot  - 0
    + Received  + 1

    @@ -43,10 +43,11 @@
        <a
          class="classes"
    +     data-discover="true"
          href="/path"
        >
          Link Text
        </a>
      </li>

      23 |   const view = render(node, options);
    > 24 |   expect(view.container.firstChild).toMatchSnapshot();
         |                                     ^
      25 | };
      26 |

      at expectMatchesSnapshot (tests/testHelpers/snapshot.ts:24:37)
      at Object.<anonymous> (tests/testHelpers/snapshot.ts:14:26)
```
</details>

As a workaround, I have a helper file with a wrapper for the React Router Link component that sets `discover="none"`. I had to change all my imports to use my custom Link instead, but that was easier than adding a prop to every Link.

```tsx
// assets/src/util/react-router.tsx
import {
  LinkProps,
  NavLinkProps,
  Link as ReactRouterLink,
  NavLink as ReactRouterNavLink,
} from "react-router";

/**
 * Use this instead of the normal react-router Link
 *
 * React Router's lazy loading / link discovery feature
 * by default adds a `data-discover="true"` attribute to every link.
 * This opts out of that feature, but must be done for every link
 * individually, hence this helper.
 *
 * It can be removed if they ever implement a global opt-out of this feature.
 * https://github.com/remix-run/react-router/issues/12656
 */
export const Link = (props: LinkProps) => (
  <ReactRouterLink discover="none" {...props} />
);
export const NavLink = (props: NavLinkProps) => (
  <ReactRouterNavLink discover="none" {...props} />
);
```

If this global opt-out is added, I can use that instead and delete my wrapper.

**Comment by llezhava** [comment]
+1 for opting out of this feature. I have offline-first web-app and this feature is complicating things for me. I have to build custom manifest file based on the routes.

**Comment by mikkpokk** [comment]
> As a workaround, I have a helper file with a wrapper for the React Router Link component that sets discover="none". I had to change all my imports to use my custom Link instead, but that was easier than adding a prop to every Link.

You probably should not apply `discover="none"` to every `Link` or `NavLink` element. Doing so causes your browser to miss the entire router manifest.

**Comment by skyqrose** [comment]
My app is not large, I don't do (and don't want to do) any code splitting or lazy loading.

**Comment by mikkpokk** [comment]
> My app is not large, I don't do (and don't want to do) any code splitting or lazy loading.

It's nothing to do with lazy loading or code splitting. When you disable the route manifest entirely (which is what you currently do by using `discover="none"` on every link), you actually increase load time. When a user now clicks on any link, RR7 will first fetch the link manifest before it can do the actual job.  

That's the problem with the issue: we are not able to load the whole route manifest on the initial load like before.

**Comment by phlipsterit** [comment]
This is also giving us a lot of trouble. I've even encountered a race condition which renders an error. Looks like it happens because there is a request for manifest of route A going in parallel to a navigation to route B.
We have a lot of links on our page, and it seems React-Router disables eager route discovery because of this. It does discovery when clicking a link, causing extra delay.
It would be nice to opt out of this, or at least be able to turn it off for a subtree of the routes, such that it does not try to get manifest for all links that navigate to the same route but with different params, like project/A, project/B, project/C etc.

We also have very few routes (but a lot of links with different params), so the strategy in the old Remix where it would get manifest of all routes in one request at startup would be much better for performance (and number of request to the server).

**Comment by mikkpokk** [comment]
@mjackson @brophdawg11 @ryanflorence Thoughts? By today, it's clear that the issue should be categorized as a 'bug' instead of 'docs'.

**Comment by c0per** [comment]
I only have a 29kb uncompressed manifest file after build. But I have a page with a lot of `navigate('/some_route/:id')` buttons.
It really is a serious overhead having to fetch /__manifest every time a button is clicked. Due to different id, the cache doesn't really solve the problem.

Event the react router doc site is calling /__manifest every time you click to navigate. FOW sure is a huge optimization for bigger site, but for a small or medium site, the network fetch overhead is also huge.

It would to nice to opt out and load the entire manifest during initial page load.

**Comment by ngbrown** [comment]
I too would like the option to just download the entire manifest in one go instead of needing to add `discover="none"` to a large list of `Link`s all going to the same module. Also, adding `discover="none"` incurs a waterfall penalty of fetching the manifest before the module on every navigation (every new id to the same module).

**Comment by brophdawg11** [comment]
We introduced a new `routeDiscovery` config in https://github.com/remix-run/react-router/pull/13451 that gives you the ability to or control the `/__manifest` path for lazy route discovery.  The new config will be available in the next release.
