### ISSUE TITLE
React Router and Nashorn evaluation throwing exception

### ISSUE THREAD

**Issue by ghost** [remix-run/react-router#550]
I am trying to evaluate the react-router in nashorn, it throwing some evaluating error as follows:
<I>
javax.script.ScriptException: ReferenceError: "setTimeout" is not defined in <eval> at line number 2963
    at jdk.nashorn.api.scripting.NashornScriptEngine.throwAsScriptException(NashornScriptEngine.java:586)
    at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:570)
    at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:525)
    at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:521)
    at jdk.nashorn.api.scripting.NashornScriptEngine.eval(NashornScriptEngine.java:192)
    at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
    at com.Application.loadReactLibraries(Application.java:36)
    at com.Application.main(Application.java:26)
Caused by: <eval>:2963 ReferenceError: "setTimeout" is not defined
    at jdk.nashorn.internal.runtime.ECMAErrors.error(ECMAErrors.java:58)
    at jdk.nashorn.internal.runtime.ECMAErrors.referenceError(ECMAErrors.java:320)
    at jdk.nashorn.internal.runtime.ECMAErrors.referenceError(ECMAErrors.java:292)
    at jdk.nashorn.api.scripting.NashornScriptEngine.**noSuchProperty**(NashornScriptEngine.java:272)
    at jdk.nashorn.internal.scripts.Script$engine.L:35(nashorn:engine/resources/engine.js:37)
    at jdk.nashorn.internal.scripts.Script$^eval_$4.L:1-1$L:2901$L:2906$L:2907$L:2945(<eval>:2963)
</I>

I am using react-router library from https://github.com/rackt/react-router/blob/master/dist/react-router.js
Is this library compatible with Nashorn ?

Cheers! Hemant

**Comment by kajmagnus** [comment]
I added this dummy function to my server side Nashorn Javascript code:

        // React-Router calls setTimeout(), but it's not available in Nashorn.
        function setTimeout(callback) {
          callback();
        }

This has been working fine for the very simple routes I've built thus far.
