### ISSUE TITLE
[Bug]: The project fails to build on a windows machine

### ISSUE THREAD

**Issue by incepter** [remix-run/react-router#8791]
### What version of React Router are you using?

latest

### Steps to Reproduce

On a windows (tested on 11) machine, perform the following:

- Fork the repo on github
- `git clone the forked repo`
- `cd react-router`
- `yarn`
- `yarn build`

### Expected Behavior

The build process to succeed

### Actual Behavior

Fails to resolve several modules, see screenshot

![image](https://user-images.githubusercontent.com/8569885/163088534-7fb34dd6-ac32-46b4-a12a-5a9743054c43.png)

Here is the command output:

```
PS C:\github\react-router> yarn build
yarn run v1.22.15
$ rollup -c && tsc -b

packages/react-router/index.ts → build/node_modules/react-router/index.js...
Browserslist: caniuse-lite is outdated. Please run:
  npx browserslist@latest --update-db
  Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
copied:
  packages/react-router/package.json → build\node_modules\react-router\package.json
  packages/react-router/README.md → build\node_modules\react-router\README.md
  LICENSE.md → build\node_modules\react-router\LICENSE.md
[!] Error: Could not resolve './lib/components' from packages\react-router\index.ts
Error: Could not resolve './lib/components' from packages\react-router\index.ts
    at error (C:\github\react-router\node_modules\rollup\dist\shared\node-entry.js:5400:30)
    at ModuleLoader.handleResolveId (C:\github\react-router\node_modules\rollup\dist\shared\node-entry.js:12410:24)
    at ModuleLoader.<anonymous> (C:\github\react-router\node_modules\rollup\dist\shared\node-entry.js:12298:30)
    at Generator.next (<anonymous>)
    at fulfilled (C:\github\react-router\node_modules\rollup\dist\shared\node-entry.js:38:28)

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

**Comment by incepter** [comment]
The build passes in a linux machine (or a docker container).

The issue still remains on the windows machine even after upgrading node and npm.

**Comment by timdorr** [comment]
Just use WSL to build it. None of us have Windows machines to verify fixes or maintain a Windows build path.

**Comment by incepter** [comment]
Yeah, that's what I ended up doing. Thanks.
