### ISSUE TITLE
[Bug]: ScrollRestoration not working

### ISSUE THREAD

**Issue by thatvegandev** [remix-run/react-router#9310]
### What version of React Router are you using?

6.4.0

### Steps to Reproduce

I have a fairly simple setup

```
<BrowserRouter>
  <Routes>
    <Route path="/" element={<App />}>
      ... more routes
    </Route>
  </Routes>
</BrowserRouter>
 ```
 
 `App.tsx`

```
<div>
  <Outlet />
  <ScrollRestoration />
</div>
```

(left out a bit for brevity, but truly nothing special)

This results in

```
utils.ts:706 Uncaught Error: useMatches must be used within a DataRouterStateContext
    at invariant (utils.ts:706:11)
    at useDataRouterState (hooks.tsx:677:3)
    at useMatches (hooks.tsx:712:33)
    at useScrollRestoration (index.tsx:990:17)
    at ScrollRestoration (index.tsx:633:3)
    at renderWithHooks (react-dom.development.js:16305:18)
    at mountIndeterminateComponent (react-dom.development.js:20074:13)
    at beginWork (react-dom.development.js:21587:16)
    at HTMLUnknownElement.callCallback2 (react-dom.development.js:4164:14)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:16)
```

### Expected Behavior

I'm familiar with ScrollRestoration from Remix – I'd think it would function more or less the same! Not sure what might be going on here.

### Actual Behavior

Refer to example above

**Comment by brophdawg11** [comment]
We need to add a note to the docs about this, but `ScrollRestoration` only works when using a `RouterProvider` (via  `createBrowserRouter` and it's siblings) since it's a function provided by the new `@remix-run/router`.  `BrowserRouter` and it's siblings from 6.3 only leverage a "history" but not the new remix router
