### ISSUE TITLE
[Bug]: Auth example is missing Router

### ISSUE THREAD

**Issue by andrecp** [remix-run/react-router#9789]
### What version of React Router are you using?

6.6.1

### Steps to Reproduce

Try to follow the docs here: https://github.com/remix-run/react-router/tree/main/examples/auth/src

It seems like it should be wrapping everything on a 

`BrowserRouter`

Otherwise..

```
history.ts:460 Uncaught Error: useRoutes() may be used only in the context of a <Router> component.
    at invariant (history.ts:460:1)
    at useRoutes (hooks.tsx:306:1)
    at Routes (components.tsx:384:1)
    at renderWithHooks (react-dom.development.js:16305:1)
    at mountIndeterminateComponent (react-dom.development.js:20074:1)
    at beginWork (react-dom.development.js:21587:1)
    at beginWork$1 (react-dom.development.js:27426:1)
    at performUnitOfWork (react-dom.development.js:26557:1)
    at workLoopSync (react-dom.development.js:26466:1)
```

### Expected Behavior

For it to work.

### Actual Behavior

It doesn't work.

**Comment by andrecp** [comment]
Argh, saw it was on main.tsx, my bad
