### ISSUE TITLE
[Bug]: createMemoryRouter is dependant on Web APIs

### ISSUE THREAD

**Issue by Yiin** [remix-run/react-router#9796]
### What version of React Router are you using?

6.6.0

### Steps to Reproduce

Create data router using `createMemoryRouter(...)` and `<RouterProvider ...>`, use redirect() or navigate() in environment that it neither test env nor a browser.

### Expected Behavior

Internal current route should change to the one provided in `redirect()` or `navigate()` (as it currently does when using `<MemoryRouter>`).

### Actual Behavior

An error is being thrown:

```
ReferenceError: window is not defined
    at createClientSideURL (/home/yiin/projects/wicked/node_modules/@remix-run/router/history.ts:570:9)
    at createClientSideRequest (/home/yiin/projects/wicked/node_modules/@remix-run/router/router.ts:2900:13)
    at startNavigation (/home/yiin/projects/wicked/node_modules/@remix-run/router/router.ts:959:19)
    at Object.navigate (/home/yiin/projects/wicked/node_modules/@remix-run/router/router.ts:859:18)
```

**Comment by stereoplegic** [comment]
Can confirm in 6.6.1.

**Comment by stereoplegic** [comment]
To shed some more light on this, my error is referring to window.location.href being undefined. I assume that's coming from RouterContext(/createHref?), not createMemoryRouter itself.

**Comment by brophdawg11** [comment]
This is released in a `6.6.3-pre.0` prerelease if you want to give it a shot.  Should have a stable out probably early next week

**Comment by stereoplegic** [comment]
@brophdawg11  can confirm createMemoryRouter is now working in React Native! TYSM!!!
