### ISSUE TITLE
[Bug]: Tests with redirect in action fails after upgrading to version 6.7.0

### ISSUE THREAD

**Issue by lasseklovstad** [remix-run/react-router#9951]
### What version of React Router are you using?

6.7.0

### Steps to Reproduce

Relevant dependencies:
```json
"devDependencies": {
    "jsdom": "21.0.0",
    "vitest": "0.27.2",
    "react-router-dom": "6.7.0",
    "react": "18.2.0",
    "react-dom": "18.2.0",
  }
```
Run this test:
```javascript
import { render, screen } from "@testing-library/react";
import { createMemoryRouter, Form, redirect, RouterProvider } from "react-router-dom";
import userEvent from "@testing-library/user-event";
import { expect } from "vitest";

it("should redirect in action", async () => {
    const mockAction = vi.fn(() => redirect("/test"));
    const router = createMemoryRouter([
      {
        path: "/",
        action: mockAction,
        element: (
          <div>
            <Form method="post">
              <button>Submit</button>
            </Form>
          </div>
        ),
      },
      {
        path: "/test",
        element: <div>Test</div>,
      },
    ]);
    render(<RouterProvider router={router} />);
    await userEvent.click(await screen.findByRole("button", { name: "Submit" }));
    expect(mockAction).toHaveBeenCalledOnce();
    expect(await screen.findByText("Test")).toBeVisible();
  });
```

### Expected Behavior

I would expect that testing navigation in unit test would work as before. Previuse versions didn't have this issue. This will make it harder to test if the redirect in an action is correct. 

### Actual Behavior

I get error message when redirecting in action and the test fails: 
```bash
Error: Not implemented: navigation (except hash changes)                                                                                                                   
    at module.exports (C:\project\node_modules\jsdom\lib\jsdom\browser\not-implemented.js:9:17)                          
    at navigateFetch (C:\project\node_modules\jsdom\lib\jsdom\living\window\navigation.js:77:3)                          
    at exports.navigate (C:\project\node_modules\jsdom\lib\jsdom\living\window\navigation.js:55:3)                       
    at LocationImpl._locationObjectNavigate (C:\project\node_modules\jsdom\lib\jsdom\living\window\Location-impl.js:31:5)
    at LocationImpl.assign (C:\project\node_modules\jsdom\lib\jsdom\living\window\Location-impl.js:211:10)               
    at Location.assign (C:\project\node_modules\jsdom\lib\jsdom\living\generated\Location.js:72:36)                      
    at startRedirectNavigation (C:\project\node_modules\@remix-run\router\router.ts:1910:27)                             
    at handleAction (C:\project\node_modules\@remix-run\router\router.ts:1267:13)                                        
    at startNavigation (C:\project\node_modules\@remix-run\router\router.ts:1155:26)                                     
    at Object.navigate (C:\project\node_modules\@remix-run\router\router.ts:1032:12) undefined    
```

Unable to find an element with the text: Test

**Comment by timdorr** [comment]
This is a jsdom issue. Please see some solutions here: jsdom/jsdom#2112
